// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * Account schema
 */
export const zAccount = z.object({
    accountCode: z.string().optional(),
    accountName: z.string().optional(),
    accountSubType: z.string().optional(),
    accountType: z.string().optional(),
    description: z.string().optional(),
    hotelId: z.int().gte(0).optional(),
    id: z.int().gte(0).optional(),
    isActive: z.boolean().optional(),
    isSystem: z.boolean().optional(),
    normalBalance: z.string().optional(),
    parentId: z.int().gte(0).optional()
});

/**
 * Expense schema
 */
export const zExpense = z.object({
    accountId: z.int().gte(0).optional(),
    amount: z.number().optional(),
    category: z.string().optional(),
    createdBy: z.int().gte(0).optional(),
    description: z.string().optional(),
    expenseDate: z.iso.datetime({ offset: true }).optional(),
    hotelId: z.int().gte(0).optional(),
    id: z.int().gte(0).optional(),
    notes: z.string().optional(),
    paymentMethod: z.string().optional(),
    paymentStatus: z.string().optional(),
    reference: z.string().optional(),
    vendor: z.string().optional()
});

/**
 * Guest schema
 */
export const zGuest = z.object({
    address: z.string().optional(),
    dateOfBirth: z.iso.datetime({ offset: true }).optional(),
    fatherName: z.string().optional(),
    firstName: z.string().min(2).max(50),
    gender: z.string().optional(),
    hotelId: z.int().gte(0).optional(),
    id: z.int().gte(0).optional(),
    idNumber: z.string().optional(),
    lastName: z.string().optional(),
    nationalId: z.string().optional(),
    nationality: z.string().optional(),
    occupation: z.string().optional(),
    phone: z.string().optional(),
    placeOfBirth: z.string().optional(),
    postalCode: z.string().optional(),
    reservations: z.array(z.object({
        breakfast: z.boolean().optional(),
        departureDate: z.iso.datetime({ offset: true }).optional(),
        destination: z.string().optional(),
        durationOfStay: z.int().optional(),
        entryDate: z.iso.datetime({ offset: true }).optional(),
        guestId: z.int().gte(0).optional(),
        guide: z.boolean().optional(),
        hotelId: z.string().optional(),
        id: z.int().gte(0).optional(),
        notes: z.string().optional(),
        numberOfPeople: z.int().optional(),
        origin: z.string().optional(),
        payment: z.object({
            agency: z.boolean().optional(),
            contractType: z.string().optional(),
            id: z.int().gte(0).optional(),
            isCash: z.boolean().optional(),
            referrer: z.string().optional(),
            reservationId: z.int().gte(0).optional()
        }).optional(),
        purposeOfTravel: z.string().optional(),
        reservationCode: z.string().optional(),
        roomPrice: z.number().optional(),
        rooms: z.array(z.object({
            amenities: z.array(z.object({
                hotelId: z.string().optional(),
                id: z.int().gte(0).optional(),
                name: z.string().optional(),
                translation: z.record(z.string(), z.string()).optional()
            })).optional(),
            basePrice: z.number().optional(),
            capacity: z.int().optional(),
            description: z.string().optional(),
            floor: z.int().optional(),
            hotelId: z.int().gte(0).optional(),
            id: z.int().gte(0).optional(),
            name: z.string().optional(),
            roomNumber: z.string().min(1),
            roomType: z.object({
                colorHex: z.string().optional(),
                hotelId: z.int().gte(0).optional(),
                id: z.int().gte(0).optional(),
                name: z.string().optional(),
                translation: z.record(z.string(), z.string()).optional()
            }).optional(),
            roomTypeId: z.int().gte(0).optional(),
            status: z.object({
                colorHex: z.string().optional(),
                hotelId: z.int().gte(0).optional(),
                id: z.int().gte(0).optional(),
                name: z.string().optional(),
                translation: z.record(z.string(), z.string()).optional()
            }).optional(),
            statusId: z.int().gte(0).optional()
        })).optional(),
        userCheckIn: z.string().optional(),
        userCheckOut: z.string().optional()
    })).optional()
});

/**
 * GuestSettlementResponse schema
 */
export const zGuestSettlementResponse = z.object({
    balance: z.number().optional(),
    parkingTransactions: z.array(z.object({
        amountDue: z.number().optional(),
        amountPaid: z.number().optional(),
        entryTime: z.string().optional(),
        exitTime: z.string().optional(),
        hoursParked: z.number().optional(),
        id: z.int().gte(0).optional(),
        licensePlate: z.string().optional(),
        rateApplied: z.number().optional(),
        status: z.string().optional()
    })).optional(),
    reservations: z.array(z.object({
        checkInDate: z.string().optional(),
        checkOutDate: z.string().optional(),
        id: z.int().gte(0).optional(),
        paidAmount: z.number().optional(),
        reservationCode: z.string().optional(),
        roomPrice: z.number().optional(),
        status: z.string().optional()
    })).optional(),
    totalDue: z.number().optional(),
    totalPaid: z.number().optional(),
    totalParking: z.number().optional(),
    totalRoom: z.number().optional()
});

/**
 * GuestWithReservationRequest schema
 */
export const zGuestWithReservationRequest = z.object({
    guest: z.object({
        address: z.string().optional(),
        dateOfBirth: z.iso.datetime({ offset: true }).optional(),
        fatherName: z.string().optional(),
        firstName: z.string().min(2).max(50),
        gender: z.string().optional(),
        hotelId: z.int().gte(0).optional(),
        id: z.int().gte(0).optional(),
        idNumber: z.string().optional(),
        lastName: z.string().optional(),
        nationalId: z.string().optional(),
        nationality: z.string().optional(),
        occupation: z.string().optional(),
        phone: z.string().optional(),
        placeOfBirth: z.string().optional(),
        postalCode: z.string().optional(),
        reservations: z.array(z.object({
            breakfast: z.boolean().optional(),
            departureDate: z.iso.datetime({ offset: true }).optional(),
            destination: z.string().optional(),
            durationOfStay: z.int().optional(),
            entryDate: z.iso.datetime({ offset: true }).optional(),
            guestId: z.int().gte(0).optional(),
            guide: z.boolean().optional(),
            hotelId: z.string().optional(),
            id: z.int().gte(0).optional(),
            notes: z.string().optional(),
            numberOfPeople: z.int().optional(),
            origin: z.string().optional(),
            payment: z.object({
                agency: z.boolean().optional(),
                contractType: z.string().optional(),
                id: z.int().gte(0).optional(),
                isCash: z.boolean().optional(),
                referrer: z.string().optional(),
                reservationId: z.int().gte(0).optional()
            }).optional(),
            purposeOfTravel: z.string().optional(),
            reservationCode: z.string().optional(),
            roomPrice: z.number().optional(),
            rooms: z.array(z.object({
                amenities: z.array(z.object({
                    hotelId: z.string().optional(),
                    id: z.int().gte(0).optional(),
                    name: z.string().optional(),
                    translation: z.record(z.string(), z.string()).optional()
                })).optional(),
                basePrice: z.number().optional(),
                capacity: z.int().optional(),
                description: z.string().optional(),
                floor: z.int().optional(),
                hotelId: z.int().gte(0).optional(),
                id: z.int().gte(0).optional(),
                name: z.string().optional(),
                roomNumber: z.string().min(1),
                roomType: z.object({
                    colorHex: z.string().optional(),
                    hotelId: z.int().gte(0).optional(),
                    id: z.int().gte(0).optional(),
                    name: z.string().optional(),
                    translation: z.record(z.string(), z.string()).optional()
                }).optional(),
                roomTypeId: z.int().gte(0).optional(),
                status: z.object({
                    colorHex: z.string().optional(),
                    hotelId: z.int().gte(0).optional(),
                    id: z.int().gte(0).optional(),
                    name: z.string().optional(),
                    translation: z.record(z.string(), z.string()).optional()
                }).optional(),
                statusId: z.int().gte(0).optional()
            })).optional(),
            userCheckIn: z.string().optional(),
            userCheckOut: z.string().optional()
        })).optional()
    }).optional(),
    payment: z.object({
        agency: z.boolean().optional(),
        contractType: z.string().optional(),
        isCash: z.boolean().optional(),
        referrer: z.string().optional()
    }).optional(),
    reservation: z.object({
        breakfast: z.boolean().optional(),
        departureDate: z.iso.datetime({ offset: true }).optional(),
        destination: z.string().optional(),
        durationOfStay: z.int().optional(),
        entryDate: z.iso.datetime({ offset: true }).optional(),
        guide: z.boolean().optional(),
        notes: z.string().optional(),
        numberOfPeople: z.int().optional(),
        origin: z.string().optional(),
        purposeOfTravel: z.string().optional(),
        reservationCode: z.string().optional(),
        roomPrice: z.number().optional(),
        rooms: z.array(z.object({
            amenities: z.array(z.object({
                hotelId: z.string().optional(),
                id: z.int().gte(0).optional(),
                name: z.string().optional(),
                translation: z.record(z.string(), z.string()).optional()
            })).optional(),
            basePrice: z.number().optional(),
            capacity: z.int().optional(),
            description: z.string().optional(),
            floor: z.int().optional(),
            hotelId: z.int().gte(0).optional(),
            id: z.int().gte(0).optional(),
            name: z.string().optional(),
            roomNumber: z.string().min(1),
            roomType: z.object({
                colorHex: z.string().optional(),
                hotelId: z.int().gte(0).optional(),
                id: z.int().gte(0).optional(),
                name: z.string().optional(),
                translation: z.record(z.string(), z.string()).optional()
            }).optional(),
            roomTypeId: z.int().gte(0).optional(),
            status: z.object({
                colorHex: z.string().optional(),
                hotelId: z.int().gte(0).optional(),
                id: z.int().gte(0).optional(),
                name: z.string().optional(),
                translation: z.record(z.string(), z.string()).optional()
            }).optional(),
            statusId: z.int().gte(0).optional()
        })).optional()
    }).optional()
});

/**
 * GuestWithReservationResponse schema
 */
export const zGuestWithReservationResponse = z.object({
    guest: z.object({
        address: z.string().optional(),
        dateOfBirth: z.iso.datetime({ offset: true }).optional(),
        fatherName: z.string().optional(),
        firstName: z.string().min(2).max(50),
        gender: z.string().optional(),
        hotelId: z.int().gte(0).optional(),
        id: z.int().gte(0).optional(),
        idNumber: z.string().optional(),
        lastName: z.string().optional(),
        nationalId: z.string().optional(),
        nationality: z.string().optional(),
        occupation: z.string().optional(),
        phone: z.string().optional(),
        placeOfBirth: z.string().optional(),
        postalCode: z.string().optional(),
        reservations: z.array(z.object({
            breakfast: z.boolean().optional(),
            departureDate: z.iso.datetime({ offset: true }).optional(),
            destination: z.string().optional(),
            durationOfStay: z.int().optional(),
            entryDate: z.iso.datetime({ offset: true }).optional(),
            guestId: z.int().gte(0).optional(),
            guide: z.boolean().optional(),
            hotelId: z.string().optional(),
            id: z.int().gte(0).optional(),
            notes: z.string().optional(),
            numberOfPeople: z.int().optional(),
            origin: z.string().optional(),
            payment: z.object({
                agency: z.boolean().optional(),
                contractType: z.string().optional(),
                id: z.int().gte(0).optional(),
                isCash: z.boolean().optional(),
                referrer: z.string().optional(),
                reservationId: z.int().gte(0).optional()
            }).optional(),
            purposeOfTravel: z.string().optional(),
            reservationCode: z.string().optional(),
            roomPrice: z.number().optional(),
            rooms: z.array(z.object({
                amenities: z.array(z.object({
                    hotelId: z.string().optional(),
                    id: z.int().gte(0).optional(),
                    name: z.string().optional(),
                    translation: z.record(z.string(), z.string()).optional()
                })).optional(),
                basePrice: z.number().optional(),
                capacity: z.int().optional(),
                description: z.string().optional(),
                floor: z.int().optional(),
                hotelId: z.int().gte(0).optional(),
                id: z.int().gte(0).optional(),
                name: z.string().optional(),
                roomNumber: z.string().min(1),
                roomType: z.object({
                    colorHex: z.string().optional(),
                    hotelId: z.int().gte(0).optional(),
                    id: z.int().gte(0).optional(),
                    name: z.string().optional(),
                    translation: z.record(z.string(), z.string()).optional()
                }).optional(),
                roomTypeId: z.int().gte(0).optional(),
                status: z.object({
                    colorHex: z.string().optional(),
                    hotelId: z.int().gte(0).optional(),
                    id: z.int().gte(0).optional(),
                    name: z.string().optional(),
                    translation: z.record(z.string(), z.string()).optional()
                }).optional(),
                statusId: z.int().gte(0).optional()
            })).optional(),
            userCheckIn: z.string().optional(),
            userCheckOut: z.string().optional()
        })).optional()
    }).optional(),
    payment: z.object({
        agency: z.boolean().optional(),
        contractType: z.string().optional(),
        id: z.int().gte(0).optional(),
        isCash: z.boolean().optional(),
        referrer: z.string().optional(),
        reservationId: z.int().gte(0).optional()
    }).optional(),
    reservation: z.object({
        breakfast: z.boolean().optional(),
        departureDate: z.iso.datetime({ offset: true }).optional(),
        destination: z.string().optional(),
        durationOfStay: z.int().optional(),
        entryDate: z.iso.datetime({ offset: true }).optional(),
        guestId: z.int().gte(0).optional(),
        guide: z.boolean().optional(),
        hotelId: z.string().optional(),
        id: z.int().gte(0).optional(),
        notes: z.string().optional(),
        numberOfPeople: z.int().optional(),
        origin: z.string().optional(),
        payment: z.object({
            agency: z.boolean().optional(),
            contractType: z.string().optional(),
            id: z.int().gte(0).optional(),
            isCash: z.boolean().optional(),
            referrer: z.string().optional(),
            reservationId: z.int().gte(0).optional()
        }).optional(),
        purposeOfTravel: z.string().optional(),
        reservationCode: z.string().optional(),
        roomPrice: z.number().optional(),
        rooms: z.array(z.object({
            amenities: z.array(z.object({
                hotelId: z.string().optional(),
                id: z.int().gte(0).optional(),
                name: z.string().optional(),
                translation: z.record(z.string(), z.string()).optional()
            })).optional(),
            basePrice: z.number().optional(),
            capacity: z.int().optional(),
            description: z.string().optional(),
            floor: z.int().optional(),
            hotelId: z.int().gte(0).optional(),
            id: z.int().gte(0).optional(),
            name: z.string().optional(),
            roomNumber: z.string().min(1),
            roomType: z.object({
                colorHex: z.string().optional(),
                hotelId: z.int().gte(0).optional(),
                id: z.int().gte(0).optional(),
                name: z.string().optional(),
                translation: z.record(z.string(), z.string()).optional()
            }).optional(),
            roomTypeId: z.int().gte(0).optional(),
            status: z.object({
                colorHex: z.string().optional(),
                hotelId: z.int().gte(0).optional(),
                id: z.int().gte(0).optional(),
                name: z.string().optional(),
                translation: z.record(z.string(), z.string()).optional()
            }).optional(),
            statusId: z.int().gte(0).optional()
        })).optional(),
        userCheckIn: z.string().optional(),
        userCheckOut: z.string().optional()
    }).optional()
});

/**
 * HTTPError schema
 */
export const zHttpError = z.object({
    detail: z.string().optional(),
    errors: z.array(z.object({
        more: z.record(z.string(), z.unknown()).optional(),
        name: z.string().optional(),
        reason: z.string().optional()
    })).optional(),
    instance: z.string().optional(),
    status: z.int().optional(),
    title: z.string().optional(),
    type: z.string().optional()
});

/**
 * Hotel schema
 */
export const zHotel = z.object({
    address: z.string().optional(),
    email: z.string().optional(),
    id: z.string().optional(),
    name: z.string().optional(),
    phone: z.string().optional()
});

/**
 * Income schema
 */
export const zIncome = z.object({
    accountId: z.int().gte(0).optional(),
    amount: z.number().optional(),
    category: z.string().optional(),
    createdBy: z.int().gte(0).optional(),
    description: z.string().optional(),
    hotelId: z.int().gte(0).optional(),
    id: z.int().gte(0).optional(),
    incomeDate: z.iso.datetime({ offset: true }).optional(),
    notes: z.string().optional(),
    paymentMethod: z.string().optional(),
    paymentStatus: z.string().optional(),
    reference: z.string().optional(),
    reservationId: z.int().gte(0).optional(),
    source: z.string().optional()
});

/**
 * MeResponse schema
 */
export const zMeResponse = z.object({
    hotelId: z.string().optional(),
    user: z.object({
        email: z.string().optional(),
        firstName: z.string().optional(),
        id: z.int().gte(0).optional(),
        lastName: z.string().optional(),
        roles: z.array(z.object({
            hotelId: z.string().optional(),
            id: z.int().gte(0).optional(),
            name: z.string().optional(),
            translation: z.record(z.string(), z.string()).optional()
        })).optional(),
        userHotels: z.array(z.object({
            hotel: z.object({
                address: z.string().optional(),
                email: z.string().optional(),
                id: z.string().optional(),
                name: z.string().optional(),
                phone: z.string().optional()
            }).optional(),
            hotelId: z.string().optional(),
            role: z.object({
                hotelId: z.string().optional(),
                id: z.int().gte(0).optional(),
                name: z.string().optional(),
                translation: z.record(z.string(), z.string()).optional()
            }).optional(),
            roleId: z.int().gte(0).optional()
        })).optional()
    }).optional(),
    userHotels: z.array(z.object({
        hotel: z.object({
            address: z.string().optional(),
            email: z.string().optional(),
            id: z.string().optional(),
            name: z.string().optional(),
            phone: z.string().optional()
        }).optional(),
        hotelId: z.string().optional(),
        role: z.object({
            hotelId: z.string().optional(),
            id: z.int().gte(0).optional(),
            name: z.string().optional(),
            translation: z.record(z.string(), z.string()).optional()
        }).optional(),
        roleId: z.int().gte(0).optional()
    })).optional()
});

/**
 * PaginatedResponse_models.Account schema
 */
export const zPaginatedResponseModelsAccount = z.object({
    data: z.array(z.object({
        accountCode: z.string().optional(),
        accountName: z.string().optional(),
        accountSubType: z.string().optional(),
        accountType: z.string().optional(),
        description: z.string().optional(),
        hotelId: z.int().gte(0).optional(),
        id: z.int().gte(0).optional(),
        isActive: z.boolean().optional(),
        isSystem: z.boolean().optional(),
        normalBalance: z.string().optional(),
        parentId: z.int().gte(0).optional()
    })).optional(),
    limit: z.int().optional(),
    page: z.int().optional(),
    total: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    totalPages: z.int().optional()
});

/**
 * PaginatedResponse_models.Amenity schema
 */
export const zPaginatedResponseModelsAmenity = z.object({
    data: z.array(z.object({
        hotelId: z.string().optional(),
        id: z.int().gte(0).optional(),
        name: z.string().optional(),
        translation: z.record(z.string(), z.string()).optional()
    })).optional(),
    limit: z.int().optional(),
    page: z.int().optional(),
    total: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    totalPages: z.int().optional()
});

/**
 * PaginatedResponse_models.Expense schema
 */
export const zPaginatedResponseModelsExpense = z.object({
    data: z.array(z.object({
        accountId: z.int().gte(0).optional(),
        amount: z.number().optional(),
        category: z.string().optional(),
        createdBy: z.int().gte(0).optional(),
        description: z.string().optional(),
        expenseDate: z.iso.datetime({ offset: true }).optional(),
        hotelId: z.int().gte(0).optional(),
        id: z.int().gte(0).optional(),
        notes: z.string().optional(),
        paymentMethod: z.string().optional(),
        paymentStatus: z.string().optional(),
        reference: z.string().optional(),
        vendor: z.string().optional()
    })).optional(),
    limit: z.int().optional(),
    page: z.int().optional(),
    total: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    totalPages: z.int().optional()
});

/**
 * PaginatedResponse_models.Guest schema
 */
export const zPaginatedResponseModelsGuest = z.object({
    data: z.array(z.object({
        address: z.string().optional(),
        dateOfBirth: z.iso.datetime({ offset: true }).optional(),
        fatherName: z.string().optional(),
        firstName: z.string().min(2).max(50),
        gender: z.string().optional(),
        hotelId: z.int().gte(0).optional(),
        id: z.int().gte(0).optional(),
        idNumber: z.string().optional(),
        lastName: z.string().optional(),
        nationalId: z.string().optional(),
        nationality: z.string().optional(),
        occupation: z.string().optional(),
        phone: z.string().optional(),
        placeOfBirth: z.string().optional(),
        postalCode: z.string().optional(),
        reservations: z.array(z.object({
            breakfast: z.boolean().optional(),
            departureDate: z.iso.datetime({ offset: true }).optional(),
            destination: z.string().optional(),
            durationOfStay: z.int().optional(),
            entryDate: z.iso.datetime({ offset: true }).optional(),
            guestId: z.int().gte(0).optional(),
            guide: z.boolean().optional(),
            hotelId: z.string().optional(),
            id: z.int().gte(0).optional(),
            notes: z.string().optional(),
            numberOfPeople: z.int().optional(),
            origin: z.string().optional(),
            payment: z.object({
                agency: z.boolean().optional(),
                contractType: z.string().optional(),
                id: z.int().gte(0).optional(),
                isCash: z.boolean().optional(),
                referrer: z.string().optional(),
                reservationId: z.int().gte(0).optional()
            }).optional(),
            purposeOfTravel: z.string().optional(),
            reservationCode: z.string().optional(),
            roomPrice: z.number().optional(),
            rooms: z.array(z.object({
                amenities: z.array(z.object({
                    hotelId: z.string().optional(),
                    id: z.int().gte(0).optional(),
                    name: z.string().optional(),
                    translation: z.record(z.string(), z.string()).optional()
                })).optional(),
                basePrice: z.number().optional(),
                capacity: z.int().optional(),
                description: z.string().optional(),
                floor: z.int().optional(),
                hotelId: z.int().gte(0).optional(),
                id: z.int().gte(0).optional(),
                name: z.string().optional(),
                roomNumber: z.string().min(1),
                roomType: z.object({
                    colorHex: z.string().optional(),
                    hotelId: z.int().gte(0).optional(),
                    id: z.int().gte(0).optional(),
                    name: z.string().optional(),
                    translation: z.record(z.string(), z.string()).optional()
                }).optional(),
                roomTypeId: z.int().gte(0).optional(),
                status: z.object({
                    colorHex: z.string().optional(),
                    hotelId: z.int().gte(0).optional(),
                    id: z.int().gte(0).optional(),
                    name: z.string().optional(),
                    translation: z.record(z.string(), z.string()).optional()
                }).optional(),
                statusId: z.int().gte(0).optional()
            })).optional(),
            userCheckIn: z.string().optional(),
            userCheckOut: z.string().optional()
        })).optional()
    })).optional(),
    limit: z.int().optional(),
    page: z.int().optional(),
    total: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    totalPages: z.int().optional()
});

/**
 * PaginatedResponse_models.Hotel schema
 */
export const zPaginatedResponseModelsHotel = z.object({
    data: z.array(z.object({
        address: z.string().optional(),
        email: z.string().optional(),
        id: z.string().optional(),
        name: z.string().optional(),
        phone: z.string().optional()
    })).optional(),
    limit: z.int().optional(),
    page: z.int().optional(),
    total: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    totalPages: z.int().optional()
});

/**
 * PaginatedResponse_models.Income schema
 */
export const zPaginatedResponseModelsIncome = z.object({
    data: z.array(z.object({
        accountId: z.int().gte(0).optional(),
        amount: z.number().optional(),
        category: z.string().optional(),
        createdBy: z.int().gte(0).optional(),
        description: z.string().optional(),
        hotelId: z.int().gte(0).optional(),
        id: z.int().gte(0).optional(),
        incomeDate: z.iso.datetime({ offset: true }).optional(),
        notes: z.string().optional(),
        paymentMethod: z.string().optional(),
        paymentStatus: z.string().optional(),
        reference: z.string().optional(),
        reservationId: z.int().gte(0).optional(),
        source: z.string().optional()
    })).optional(),
    limit: z.int().optional(),
    page: z.int().optional(),
    total: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    totalPages: z.int().optional()
});

/**
 * PaginatedResponse_models.ParkingLot schema
 */
export const zPaginatedResponseModelsParkingLot = z.object({
    data: z.array(z.object({
        dailyRate: z.number().optional(),
        description: z.string().optional(),
        hotelId: z.int().gte(0).optional(),
        hourlyRate: z.number().optional(),
        id: z.int().gte(0).optional(),
        location: z.string().optional(),
        name: z.string().optional(),
        status: z.string().optional(),
        totalSpots: z.int().optional()
    })).optional(),
    limit: z.int().optional(),
    page: z.int().optional(),
    total: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    totalPages: z.int().optional()
});

/**
 * PaginatedResponse_models.ParkingSpot schema
 */
export const zPaginatedResponseModelsParkingSpot = z.object({
    data: z.array(z.object({
        description: z.string().optional(),
        floor: z.string().optional(),
        id: z.int().gte(0).optional(),
        isCovered: z.boolean().optional(),
        lotId: z.int().gte(0).optional(),
        spotNumber: z.string().optional(),
        spotType: z.string().optional(),
        status: z.string().optional()
    })).optional(),
    limit: z.int().optional(),
    page: z.int().optional(),
    total: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    totalPages: z.int().optional()
});

/**
 * PaginatedResponse_models.ParkingSpotStatus schema
 */
export const zPaginatedResponseModelsParkingSpotStatus = z.object({
    data: z.array(z.object({
        hotelId: z.string().optional(),
        id: z.int().gte(0).optional(),
        name: z.string().optional(),
        translation: z.record(z.string(), z.string()).optional()
    })).optional(),
    limit: z.int().optional(),
    page: z.int().optional(),
    total: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    totalPages: z.int().optional()
});

/**
 * PaginatedResponse_models.ParkingSpotType schema
 */
export const zPaginatedResponseModelsParkingSpotType = z.object({
    data: z.array(z.object({
        hotelId: z.string().optional(),
        id: z.int().gte(0).optional(),
        name: z.string().optional(),
        translation: z.record(z.string(), z.string()).optional()
    })).optional(),
    limit: z.int().optional(),
    page: z.int().optional(),
    total: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    totalPages: z.int().optional()
});

/**
 * PaginatedResponse_models.ParkingTransaction schema
 */
export const zPaginatedResponseModelsParkingTransaction = z.object({
    data: z.array(z.object({
        amountDue: z.number().optional(),
        amountPaid: z.number().optional(),
        entryTime: z.iso.datetime({ offset: true }).optional(),
        exitTime: z.iso.datetime({ offset: true }).optional(),
        guestId: z.int().gte(0).optional(),
        hoursParked: z.number().optional(),
        id: z.int().gte(0).optional(),
        licensePlate: z.string().optional(),
        lotId: z.int().gte(0).optional(),
        notes: z.string().optional(),
        paymentMethod: z.string().optional(),
        paymentStatus: z.string().optional(),
        rateApplied: z.number().optional(),
        reservationId: z.int().gte(0).optional(),
        spotId: z.int().gte(0).optional(),
        status: z.string().optional()
    })).optional(),
    limit: z.int().optional(),
    page: z.int().optional(),
    total: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    totalPages: z.int().optional()
});

/**
 * PaginatedResponse_models.Reservation schema
 */
export const zPaginatedResponseModelsReservation = z.object({
    data: z.array(z.object({
        breakfast: z.boolean().optional(),
        departureDate: z.iso.datetime({ offset: true }).optional(),
        destination: z.string().optional(),
        durationOfStay: z.int().optional(),
        entryDate: z.iso.datetime({ offset: true }).optional(),
        guestId: z.int().gte(0).optional(),
        guide: z.boolean().optional(),
        hotelId: z.string().optional(),
        id: z.int().gte(0).optional(),
        notes: z.string().optional(),
        numberOfPeople: z.int().optional(),
        origin: z.string().optional(),
        payment: z.object({
            agency: z.boolean().optional(),
            contractType: z.string().optional(),
            id: z.int().gte(0).optional(),
            isCash: z.boolean().optional(),
            referrer: z.string().optional(),
            reservationId: z.int().gte(0).optional()
        }).optional(),
        purposeOfTravel: z.string().optional(),
        reservationCode: z.string().optional(),
        roomPrice: z.number().optional(),
        rooms: z.array(z.object({
            amenities: z.array(z.object({
                hotelId: z.string().optional(),
                id: z.int().gte(0).optional(),
                name: z.string().optional(),
                translation: z.record(z.string(), z.string()).optional()
            })).optional(),
            basePrice: z.number().optional(),
            capacity: z.int().optional(),
            description: z.string().optional(),
            floor: z.int().optional(),
            hotelId: z.int().gte(0).optional(),
            id: z.int().gte(0).optional(),
            name: z.string().optional(),
            roomNumber: z.string().min(1),
            roomType: z.object({
                colorHex: z.string().optional(),
                hotelId: z.int().gte(0).optional(),
                id: z.int().gte(0).optional(),
                name: z.string().optional(),
                translation: z.record(z.string(), z.string()).optional()
            }).optional(),
            roomTypeId: z.int().gte(0).optional(),
            status: z.object({
                colorHex: z.string().optional(),
                hotelId: z.int().gte(0).optional(),
                id: z.int().gte(0).optional(),
                name: z.string().optional(),
                translation: z.record(z.string(), z.string()).optional()
            }).optional(),
            statusId: z.int().gte(0).optional()
        })).optional(),
        userCheckIn: z.string().optional(),
        userCheckOut: z.string().optional()
    })).optional(),
    limit: z.int().optional(),
    page: z.int().optional(),
    total: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    totalPages: z.int().optional()
});

/**
 * PaginatedResponse_models.Room schema
 */
export const zPaginatedResponseModelsRoom = z.object({
    data: z.array(z.object({
        amenities: z.array(z.object({
            hotelId: z.string().optional(),
            id: z.int().gte(0).optional(),
            name: z.string().optional(),
            translation: z.record(z.string(), z.string()).optional()
        })).optional(),
        basePrice: z.number().optional(),
        capacity: z.int().optional(),
        description: z.string().optional(),
        floor: z.int().optional(),
        hotelId: z.int().gte(0).optional(),
        id: z.int().gte(0).optional(),
        name: z.string().optional(),
        roomNumber: z.string().min(1),
        roomType: z.object({
            colorHex: z.string().optional(),
            hotelId: z.int().gte(0).optional(),
            id: z.int().gte(0).optional(),
            name: z.string().optional(),
            translation: z.record(z.string(), z.string()).optional()
        }).optional(),
        roomTypeId: z.int().gte(0).optional(),
        status: z.object({
            colorHex: z.string().optional(),
            hotelId: z.int().gte(0).optional(),
            id: z.int().gte(0).optional(),
            name: z.string().optional(),
            translation: z.record(z.string(), z.string()).optional()
        }).optional(),
        statusId: z.int().gte(0).optional()
    })).optional(),
    limit: z.int().optional(),
    page: z.int().optional(),
    total: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    totalPages: z.int().optional()
});

/**
 * PaginatedResponse_models.RoomStatus schema
 */
export const zPaginatedResponseModelsRoomStatus = z.object({
    data: z.array(z.object({
        colorHex: z.string().optional(),
        hotelId: z.int().gte(0).optional(),
        id: z.int().gte(0).optional(),
        name: z.string().optional(),
        translation: z.record(z.string(), z.string()).optional()
    })).optional(),
    limit: z.int().optional(),
    page: z.int().optional(),
    total: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    totalPages: z.int().optional()
});

/**
 * PaginatedResponse_models.RoomType schema
 */
export const zPaginatedResponseModelsRoomType = z.object({
    data: z.array(z.object({
        colorHex: z.string().optional(),
        hotelId: z.int().gte(0).optional(),
        id: z.int().gte(0).optional(),
        name: z.string().optional(),
        translation: z.record(z.string(), z.string()).optional()
    })).optional(),
    limit: z.int().optional(),
    page: z.int().optional(),
    total: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    totalPages: z.int().optional()
});

/**
 * PaginatedResponse_models.Vehicle schema
 */
export const zPaginatedResponseModelsVehicle = z.object({
    data: z.array(z.object({
        color: z.string().optional(),
        guestId: z.int().gte(0).optional(),
        id: z.int().gte(0).optional(),
        isRegistered: z.boolean().optional(),
        licensePlate: z.string().optional(),
        make: z.string().optional(),
        model: z.string().optional(),
        notes: z.string().optional(),
        vehicleType: z.string().optional()
    })).optional(),
    limit: z.int().optional(),
    page: z.int().optional(),
    total: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    totalPages: z.int().optional()
});

/**
 * ParkingLot schema
 */
export const zParkingLot = z.object({
    dailyRate: z.number().optional(),
    description: z.string().optional(),
    hotelId: z.int().gte(0).optional(),
    hourlyRate: z.number().optional(),
    id: z.int().gte(0).optional(),
    location: z.string().optional(),
    name: z.string().optional(),
    status: z.string().optional(),
    totalSpots: z.int().optional()
});

/**
 * ParkingSpot schema
 */
export const zParkingSpot = z.object({
    description: z.string().optional(),
    floor: z.string().optional(),
    id: z.int().gte(0).optional(),
    isCovered: z.boolean().optional(),
    lotId: z.int().gte(0).optional(),
    spotNumber: z.string().optional(),
    spotType: z.string().optional(),
    status: z.string().optional()
});

/**
 * ParkingStats schema
 */
export const zParkingStats = z.object({
    availableSpots: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    lots: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    spots: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional()
});

/**
 * ParkingTransaction schema
 */
export const zParkingTransaction = z.object({
    amountDue: z.number().optional(),
    amountPaid: z.number().optional(),
    entryTime: z.iso.datetime({ offset: true }).optional(),
    exitTime: z.iso.datetime({ offset: true }).optional(),
    guestId: z.int().gte(0).optional(),
    hoursParked: z.number().optional(),
    id: z.int().gte(0).optional(),
    licensePlate: z.string().optional(),
    lotId: z.int().gte(0).optional(),
    notes: z.string().optional(),
    paymentMethod: z.string().optional(),
    paymentStatus: z.string().optional(),
    rateApplied: z.number().optional(),
    reservationId: z.int().gte(0).optional(),
    spotId: z.int().gte(0).optional(),
    status: z.string().optional()
});

/**
 * Reservation schema
 */
export const zReservation = z.object({
    breakfast: z.boolean().optional(),
    departureDate: z.iso.datetime({ offset: true }).optional(),
    destination: z.string().optional(),
    durationOfStay: z.int().optional(),
    entryDate: z.iso.datetime({ offset: true }).optional(),
    guestId: z.int().gte(0).optional(),
    guide: z.boolean().optional(),
    hotelId: z.string().optional(),
    id: z.int().gte(0).optional(),
    notes: z.string().optional(),
    numberOfPeople: z.int().optional(),
    origin: z.string().optional(),
    payment: z.object({
        agency: z.boolean().optional(),
        contractType: z.string().optional(),
        id: z.int().gte(0).optional(),
        isCash: z.boolean().optional(),
        referrer: z.string().optional(),
        reservationId: z.int().gte(0).optional()
    }).optional(),
    purposeOfTravel: z.string().optional(),
    reservationCode: z.string().optional(),
    roomPrice: z.number().optional(),
    rooms: z.array(z.object({
        amenities: z.array(z.object({
            hotelId: z.string().optional(),
            id: z.int().gte(0).optional(),
            name: z.string().optional(),
            translation: z.record(z.string(), z.string()).optional()
        })).optional(),
        basePrice: z.number().optional(),
        capacity: z.int().optional(),
        description: z.string().optional(),
        floor: z.int().optional(),
        hotelId: z.int().gte(0).optional(),
        id: z.int().gte(0).optional(),
        name: z.string().optional(),
        roomNumber: z.string().min(1),
        roomType: z.object({
            colorHex: z.string().optional(),
            hotelId: z.int().gte(0).optional(),
            id: z.int().gte(0).optional(),
            name: z.string().optional(),
            translation: z.record(z.string(), z.string()).optional()
        }).optional(),
        roomTypeId: z.int().gte(0).optional(),
        status: z.object({
            colorHex: z.string().optional(),
            hotelId: z.int().gte(0).optional(),
            id: z.int().gte(0).optional(),
            name: z.string().optional(),
            translation: z.record(z.string(), z.string()).optional()
        }).optional(),
        statusId: z.int().gte(0).optional()
    })).optional(),
    userCheckIn: z.string().optional(),
    userCheckOut: z.string().optional()
});

/**
 * Room schema
 */
export const zRoom = z.object({
    amenities: z.array(z.object({
        hotelId: z.string().optional(),
        id: z.int().gte(0).optional(),
        name: z.string().optional(),
        translation: z.record(z.string(), z.string()).optional()
    })).optional(),
    basePrice: z.number().optional(),
    capacity: z.int().optional(),
    description: z.string().optional(),
    floor: z.int().optional(),
    hotelId: z.int().gte(0).optional(),
    id: z.int().gte(0).optional(),
    name: z.string().optional(),
    roomNumber: z.string().min(1),
    roomType: z.object({
        colorHex: z.string().optional(),
        hotelId: z.int().gte(0).optional(),
        id: z.int().gte(0).optional(),
        name: z.string().optional(),
        translation: z.record(z.string(), z.string()).optional()
    }).optional(),
    roomTypeId: z.int().gte(0).optional(),
    status: z.object({
        colorHex: z.string().optional(),
        hotelId: z.int().gte(0).optional(),
        id: z.int().gte(0).optional(),
        name: z.string().optional(),
        translation: z.record(z.string(), z.string()).optional()
    }).optional(),
    statusId: z.int().gte(0).optional()
});

/**
 * SettleGuestRequest schema
 */
export const zSettleGuestRequest = z.object({
    amount: z.number().optional(),
    notes: z.string().optional(),
    parkingTxnIds: z.array(z.int().gte(0)).optional(),
    paymentMethod: z.string().optional(),
    reference: z.string().optional(),
    reservationIds: z.array(z.int().gte(0)).optional()
});

/**
 * UserHotelResponse schema
 */
export const zUserHotelResponse = z.object({
    hotelId: z.string().optional(),
    userHotels: z.array(z.object({
        hotel: z.object({
            address: z.string().optional(),
            email: z.string().optional(),
            id: z.string().optional(),
            name: z.string().optional(),
            phone: z.string().optional()
        }).optional(),
        hotelId: z.string().optional(),
        role: z.object({
            hotelId: z.string().optional(),
            id: z.int().gte(0).optional(),
            name: z.string().optional(),
            translation: z.record(z.string(), z.string()).optional()
        }).optional(),
        roleId: z.int().gte(0).optional()
    })).optional()
});

/**
 * Vehicle schema
 */
export const zVehicle = z.object({
    color: z.string().optional(),
    guestId: z.int().gte(0).optional(),
    id: z.int().gte(0).optional(),
    isRegistered: z.boolean().optional(),
    licensePlate: z.string().optional(),
    make: z.string().optional(),
    model: z.string().optional(),
    notes: z.string().optional(),
    vehicleType: z.string().optional()
});

/**
 * bool schema
 */
export const zBool = z.boolean();

/**
 * loginDto schema
 */
export const zLoginDto = z.object({
    email: z.string().optional(),
    password: z.string().optional()
});

/**
 * loginResponse schema
 */
export const zLoginResponse = z.object({
    hotelId: z.string().optional(),
    user: z.object({
        email: z.string().optional(),
        firstName: z.string().optional(),
        id: z.int().gte(0).optional(),
        lastName: z.string().optional(),
        roles: z.array(z.object({
            hotelId: z.string().optional(),
            id: z.int().gte(0).optional(),
            name: z.string().optional(),
            translation: z.record(z.string(), z.string()).optional()
        })).optional(),
        userHotels: z.array(z.object({
            hotel: z.object({
                address: z.string().optional(),
                email: z.string().optional(),
                id: z.string().optional(),
                name: z.string().optional(),
                phone: z.string().optional()
            }).optional(),
            hotelId: z.string().optional(),
            role: z.object({
                hotelId: z.string().optional(),
                id: z.int().gte(0).optional(),
                name: z.string().optional(),
                translation: z.record(z.string(), z.string()).optional()
            }).optional(),
            roleId: z.int().gte(0).optional()
        })).optional()
    }).optional()
});

/**
 * okResponse schema
 */
export const zOkResponse = z.unknown();

/**
 * string schema
 */
export const zString = z.string();

/**
 * unknown-interface schema
 */
export const zUnknownInterface = z.unknown();

/**
 * userCreateDto schema
 */
export const zUserCreateDto = z.object({
    email: z.string().optional(),
    firstName: z.string().optional(),
    lastName: z.string().optional(),
    password: z.string().optional(),
    roles: z.array(z.object({
        hotelId: z.string().optional(),
        id: z.int().gte(0).optional(),
        name: z.string().optional(),
        translation: z.record(z.string(), z.string()).optional()
    })).optional()
});

/**
 * userCreateResponse schema
 */
export const zUserCreateResponse = z.unknown();

/**
 * userListResponse schema
 */
export const zUserListResponse = z.object({
    data: z.array(z.object({
        email: z.string().optional(),
        firstName: z.string().optional(),
        id: z.int().gte(0).optional(),
        lastName: z.string().optional(),
        roles: z.array(z.object({
            hotelId: z.string().optional(),
            id: z.int().gte(0).optional(),
            name: z.string().optional(),
            translation: z.record(z.string(), z.string()).optional()
        })).optional(),
        userHotels: z.array(z.object({
            hotel: z.object({
                address: z.string().optional(),
                email: z.string().optional(),
                id: z.string().optional(),
                name: z.string().optional(),
                phone: z.string().optional()
            }).optional(),
            hotelId: z.string().optional(),
            role: z.object({
                hotelId: z.string().optional(),
                id: z.int().gte(0).optional(),
                name: z.string().optional(),
                translation: z.record(z.string(), z.string()).optional()
            }).optional(),
            roleId: z.int().gte(0).optional()
        })).optional()
    })).optional()
});

export const zGetApiAccountingAccountsHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiAccountingAccountsQuery = z.object({
    limit: z.int().optional(),
    page: z.int().optional()
});

/**
 * OK
 */
export const zGetApiAccountingAccountsResponse = zPaginatedResponseModelsAccount;

/**
 * Request body for models.Account
 */
export const zPostApiAccountingAccountsBody = zAccount;

export const zPostApiAccountingAccountsHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zPostApiAccountingAccountsResponse = zAccount;

export const zGetApiAccountingExpensesHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiAccountingExpensesQuery = z.object({
    limit: z.int().optional(),
    page: z.int().optional()
});

/**
 * OK
 */
export const zGetApiAccountingExpensesResponse = zPaginatedResponseModelsExpense;

/**
 * Request body for models.Expense
 */
export const zPostApiAccountingExpensesBody = zExpense;

export const zPostApiAccountingExpensesHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zPostApiAccountingExpensesResponse = zExpense;

export const zGetApiAccountingIncomeHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiAccountingIncomeQuery = z.object({
    limit: z.int().optional(),
    page: z.int().optional()
});

/**
 * OK
 */
export const zGetApiAccountingIncomeResponse = zPaginatedResponseModelsIncome;

/**
 * Request body for models.Income
 */
export const zPostApiAccountingIncomeBody = zIncome;

export const zPostApiAccountingIncomeHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zPostApiAccountingIncomeResponse = zIncome;

/**
 * Request body for auth.loginDto
 */
export const zPostApiAuthLoginBody = zLoginDto;

export const zPostApiAuthLoginHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zPostApiAuthLoginResponse = zLoginResponse;

export const zPostApiAuthLogoutHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zPostApiAuthLogoutResponse = zBool;

export const zGetApiAuthMeHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zGetApiAuthMeResponse = zMeResponse;

export const zGetApiGuestsHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiGuestsQuery = z.object({
    limit: z.int().optional(),
    page: z.int().optional()
});

/**
 * OK
 */
export const zGetApiGuestsResponse = zPaginatedResponseModelsGuest;

/**
 * Request body for models.Guest
 */
export const zPostApiGuestsBody = zGuest;

export const zPostApiGuestsHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zPostApiGuestsResponse = zGuest;

/**
 * Request body for guests.GuestWithReservationRequest
 */
export const zPostApiGuestsWithReservationBody = zGuestWithReservationRequest;

export const zPostApiGuestsWithReservationHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zPostApiGuestsWithReservationResponse = zGuestWithReservationResponse;

export const zGetApiGuestsIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiGuestsIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zGetApiGuestsIdResponse = zGuest;

/**
 * Request body for models.Guest
 */
export const zPutApiGuestsIdBody = zGuest;

export const zPutApiGuestsIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zPutApiGuestsIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zPutApiGuestsIdResponse = zGuest;

export const zGetApiGuestsIdSettleHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiGuestsIdSettlePath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zGetApiGuestsIdSettleResponse = zGuestSettlementResponse;

/**
 * Request body for guests.SettleGuestRequest
 */
export const zPostApiGuestsIdSettleBody = zSettleGuestRequest;

export const zPostApiGuestsIdSettleHeaders = z.object({
    Accept: z.string().optional()
});

export const zPostApiGuestsIdSettlePath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zPostApiGuestsIdSettleResponse = zOkResponse;

export const zGetApiHealthzHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zGetApiHealthzResponse = zString;

export const zGetApiHotelsHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiHotelsQuery = z.object({
    limit: z.int().optional(),
    page: z.int().optional()
});

/**
 * OK
 */
export const zGetApiHotelsResponse = zPaginatedResponseModelsHotel;

/**
 * Request body for models.Hotel
 */
export const zPostApiHotelsBody = zHotel;

export const zPostApiHotelsHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zPostApiHotelsResponse = zHotel;

export const zGetApiHotelsMyHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zGetApiHotelsMyResponse = zUserHotelResponse;

export const zDeleteApiHotelsIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zDeleteApiHotelsIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zDeleteApiHotelsIdResponse = zOkResponse;

export const zGetApiHotelsIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiHotelsIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zGetApiHotelsIdResponse = zHotel;

/**
 * Request body for models.Hotel
 */
export const zPutApiHotelsIdBody = zHotel;

export const zPutApiHotelsIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zPutApiHotelsIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zPutApiHotelsIdResponse = zHotel;

export const zGetApiParkingLotsHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiParkingLotsQuery = z.object({
    limit: z.int().optional(),
    page: z.int().optional()
});

/**
 * OK
 */
export const zGetApiParkingLotsResponse = zPaginatedResponseModelsParkingLot;

/**
 * Request body for models.ParkingLot
 */
export const zPostApiParkingLotsBody = zParkingLot;

export const zPostApiParkingLotsHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zPostApiParkingLotsResponse = zParkingLot;

export const zDeleteApiParkingLotsIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zDeleteApiParkingLotsIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zDeleteApiParkingLotsIdResponse = zOkResponse;

export const zGetApiParkingLotsIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiParkingLotsIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zGetApiParkingLotsIdResponse = zParkingLot;

/**
 * Request body for models.ParkingLot
 */
export const zPutApiParkingLotsIdBody = zParkingLot;

export const zPutApiParkingLotsIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zPutApiParkingLotsIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zPutApiParkingLotsIdResponse = zParkingLot;

export const zGetApiParkingSpotsHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiParkingSpotsQuery = z.object({
    limit: z.int().optional(),
    page: z.int().optional()
});

/**
 * OK
 */
export const zGetApiParkingSpotsResponse = zPaginatedResponseModelsParkingSpot;

/**
 * Request body for models.ParkingSpot
 */
export const zPostApiParkingSpotsBody = zParkingSpot;

export const zPostApiParkingSpotsHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zPostApiParkingSpotsResponse = zParkingSpot;

export const zGetApiParkingSpotsStatusesHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiParkingSpotsStatusesQuery = z.object({
    limit: z.int().optional(),
    page: z.int().optional()
});

/**
 * OK
 */
export const zGetApiParkingSpotsStatusesResponse = zPaginatedResponseModelsParkingSpotStatus;

export const zGetApiParkingSpotsTypesHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiParkingSpotsTypesQuery = z.object({
    limit: z.int().optional(),
    page: z.int().optional()
});

/**
 * OK
 */
export const zGetApiParkingSpotsTypesResponse = zPaginatedResponseModelsParkingSpotType;

export const zDeleteApiParkingSpotsIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zDeleteApiParkingSpotsIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zDeleteApiParkingSpotsIdResponse = zOkResponse;

export const zGetApiParkingSpotsIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiParkingSpotsIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zGetApiParkingSpotsIdResponse = zParkingSpot;

/**
 * Request body for models.ParkingSpot
 */
export const zPutApiParkingSpotsIdBody = zParkingSpot;

export const zPutApiParkingSpotsIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zPutApiParkingSpotsIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zPutApiParkingSpotsIdResponse = zParkingSpot;

export const zGetApiParkingStatsHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zGetApiParkingStatsResponse = zParkingStats;

export const zGetApiParkingTransactionsHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiParkingTransactionsQuery = z.object({
    limit: z.int().optional(),
    page: z.int().optional()
});

/**
 * OK
 */
export const zGetApiParkingTransactionsResponse = zPaginatedResponseModelsParkingTransaction;

/**
 * Request body for models.ParkingTransaction
 */
export const zPostApiParkingTransactionsBody = zParkingTransaction;

export const zPostApiParkingTransactionsHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zPostApiParkingTransactionsResponse = zParkingTransaction;

export const zGetApiParkingTransactionsIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiParkingTransactionsIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zGetApiParkingTransactionsIdResponse = zParkingTransaction;

export const zPostApiParkingTransactionsIdCheckOutHeaders = z.object({
    Accept: z.string().optional()
});

export const zPostApiParkingTransactionsIdCheckOutPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zPostApiParkingTransactionsIdCheckOutResponse = zBool;

export const zGetApiParkingVehiclesHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiParkingVehiclesQuery = z.object({
    limit: z.int().optional(),
    page: z.int().optional()
});

/**
 * OK
 */
export const zGetApiParkingVehiclesResponse = zPaginatedResponseModelsVehicle;

/**
 * Request body for models.Vehicle
 */
export const zPostApiParkingVehiclesBody = zVehicle;

export const zPostApiParkingVehiclesHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zPostApiParkingVehiclesResponse = zVehicle;

export const zDeleteApiParkingVehiclesIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zDeleteApiParkingVehiclesIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zDeleteApiParkingVehiclesIdResponse = zOkResponse;

export const zGetApiParkingVehiclesIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiParkingVehiclesIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zGetApiParkingVehiclesIdResponse = zVehicle;

/**
 * Request body for models.Vehicle
 */
export const zPutApiParkingVehiclesIdBody = zVehicle;

export const zPutApiParkingVehiclesIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zPutApiParkingVehiclesIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zPutApiParkingVehiclesIdResponse = zVehicle;

export const zGetApiReadyzHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zGetApiReadyzResponse = zString;

export const zGetApiReservationHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiReservationQuery = z.object({
    limit: z.int().optional(),
    page: z.int().optional()
});

/**
 * OK
 */
export const zGetApiReservationResponse = zPaginatedResponseModelsReservation;

/**
 * Request body for models.Reservation
 */
export const zPostApiReservationBody = zReservation;

export const zPostApiReservationHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zPostApiReservationResponse = zReservation;

export const zGetApiReservationIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiReservationIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zGetApiReservationIdResponse = zReservation;

/**
 * Request body for models.Reservation
 */
export const zPutApiReservationIdBody = zReservation;

export const zPutApiReservationIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zPutApiReservationIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zPutApiReservationIdResponse = zReservation;

export const zPostApiReservationIdCheckInHeaders = z.object({
    Accept: z.string().optional()
});

export const zPostApiReservationIdCheckInPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zPostApiReservationIdCheckInResponse = zOkResponse;

export const zPostApiReservationIdCheckOutHeaders = z.object({
    Accept: z.string().optional()
});

export const zPostApiReservationIdCheckOutPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zPostApiReservationIdCheckOutResponse = zOkResponse;

export const zGetApiRoomsHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiRoomsQuery = z.object({
    limit: z.int().optional(),
    page: z.int().optional()
});

/**
 * OK
 */
export const zGetApiRoomsResponse = zPaginatedResponseModelsRoom;

/**
 * Request body for models.Room
 */
export const zPostApiRoomsBody = zRoom;

export const zPostApiRoomsHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zPostApiRoomsResponse = zRoom;

export const zGetApiRoomsAmenitiesHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiRoomsAmenitiesQuery = z.object({
    limit: z.int().optional(),
    page: z.int().optional()
});

/**
 * OK
 */
export const zGetApiRoomsAmenitiesResponse = zPaginatedResponseModelsAmenity;

export const zGetApiRoomsStatusesHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiRoomsStatusesQuery = z.object({
    limit: z.int().optional(),
    page: z.int().optional()
});

/**
 * OK
 */
export const zGetApiRoomsStatusesResponse = zPaginatedResponseModelsRoomStatus;

export const zGetApiRoomsTypesHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiRoomsTypesQuery = z.object({
    limit: z.int().optional(),
    page: z.int().optional()
});

/**
 * OK
 */
export const zGetApiRoomsTypesResponse = zPaginatedResponseModelsRoomType;

export const zDeleteApiRoomsIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zDeleteApiRoomsIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zDeleteApiRoomsIdResponse = zOkResponse;

export const zGetApiRoomsIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiRoomsIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zGetApiRoomsIdResponse = zRoom;

/**
 * Request body for models.Room
 */
export const zPutApiRoomsIdBody = zRoom;

export const zPutApiRoomsIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zPutApiRoomsIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zPutApiRoomsIdResponse = zRoom;

export const zGetApiUsersHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zGetApiUsersResponse = zUserListResponse;

/**
 * Request body for users.userCreateDto
 */
export const zPostApiUsersBody = zUserCreateDto;

export const zPostApiUsersHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zPostApiUsersResponse = zUserCreateResponse;
