services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6767:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/hotel
      - NUXT_PUBLIC_HOTEL_NAME=Hotel Management System
    networks:
      - postgres_network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: hub.megan.ir/postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hotel
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - postgres_network

  pgadmin:
    image: docker.hyperclouds.ir/dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - postgres_network
    depends_on:
      - db

volumes:
  postgres_data:
  pgadmin_data:

networks:
  postgres_network:
    driver: bridge
