//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"log"
	"os"
	"strings"
	"text/template"
)

const modelsDir = "."
const outputFile = "./translatables_gen.go" // or generate per struct file

type fieldInfo struct {
	Name     string
	IsSlice  bool
	IsStruct bool // for single struct field (non-slice)
}

type structInfo struct {
	Name   string
	Fields []fieldInfo
}

func main() {
	// Parse the models package (current directory or specify path)

	dir, err := os.Getwd()
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(dir)
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, modelsDir, nil, parser.ParseComments)
	if err != nil {
		log.Fatal(err)
	}

	var structs []structInfo

	for _, pkg := range pkgs {
		for _, file := range pkg.Files {
			ast.Inspect(file, func(n ast.Node) bool {
				ts, ok := n.(*ast.TypeSpec)
				if !ok {
					return true
				}
				st, ok := ts.Type.(*ast.StructType)
				if !ok {
					return true
				}

				var fields []fieldInfo
				for _, field := range st.Fields.List {
					// Check for translate tag
					if field.Tag == nil {
						continue
					}
					tag := strings.Trim(field.Tag.Value, "`")
					if !strings.Contains(tag, `translate:"true"`) {
						continue
					}

					// Determine field type (simple heuristic)
					var fieldInfo fieldInfo
					fieldInfo.Name = field.Names[0].Name // assumes at least one name

					switch field.Type.(type) {
					case *ast.Ident:
						// Single struct (e.g., RoomType)
						fieldInfo.IsStruct = true
						fieldInfo.IsSlice = false
					case *ast.ArrayType:
						// Slice of something - we assume it's a slice of structs
						fieldInfo.IsSlice = true
						fieldInfo.IsStruct = false
					default:
						// Ignore other types (map, chan, etc.) or handle as needed
						continue
					}
					fields = append(fields, fieldInfo)
				}

				if len(fields) > 0 {
					structs = append(structs, structInfo{
						Name:   ts.Name.Name,
						Fields: fields,
					})
				}
				return true
			})
		}
	}

	if len(structs) == 0 {
		log.Println("No structs with translatable fields found")
		return
	}

	// Generate code
	genFile, err := os.Create(outputFile)
	if err != nil {
		log.Fatal(err)
	}
	defer genFile.Close()

	inititals := `// Code generated by "models/generate"; DO NOT EDIT.
package models

`

	tmpl := `func (m *{{.Name}}) GetTranslatables() []Translatable {
    var res []Translatable
{{range .Fields}}
{{- if .IsStruct}}
    res = append(res, &m.{{.Name}})
{{- else if .IsSlice}}
    for i := range m.{{.Name}} {
        res = append(res, &m.{{.Name}}[i])
    }
{{- end}}
{{end}}
    return res
}
`
	genFile.WriteString(inititals)

	t := template.Must(template.New("method").Parse(tmpl))
	for _, s := range structs {
		var buf bytes.Buffer
		if err := t.Execute(&buf, s); err != nil {
			log.Fatal(err)
		}
		if _, err := genFile.Write(buf.Bytes()); err != nil {
			log.Fatal(err)
		}
		// Add a newline between methods
		fmt.Fprintln(genFile)
	}
	fmt.Printf("Generated GetTranslatables for %d structs in %s\n", len(structs), outputFile)
}
