// Code generated by "models/generate"; DO NOT EDIT.
package models

func (m *User) GetTranslatables() []Translatable {
    var res []Translatable

    for i := range m.Roles {
        res = append(res, &m.Roles[i])
    }

    return res
}

func (m *Room) GetTranslatables() []Translatable {
    var res []Translatable

    for i := range m.Amenities {
        res = append(res, &m.Amenities[i])
    }

    res = append(res, &m.Type)

    res = append(res, &m.Status)

    return res
}

