// Code generated by "models/generate"; DO NOT EDIT.
package models

func (m *Expense) GetTranslatables() []Translatable {
    var res []Translatable

    res = append(res, &m.Category)

    res = append(res, &m.PaymentMethod)

    return res
}

func (m *Income) GetTranslatables() []Translatable {
    var res []Translatable

    res = append(res, &m.PaymentMethod)

    res = append(res, &m.Category)

    return res
}

func (m *ParkingTransaction) GetTranslatables() []Translatable {
    var res []Translatable

    res = append(res, &m.PaymentMethod)

    return res
}

func (m *Room) GetTranslatables() []Translatable {
    var res []Translatable

    for i := range m.Amenities {
        res = append(res, &m.Amenities[i])
    }

    res = append(res, &m.Type)

    res = append(res, &m.Status)

    return res
}

