// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `http://${string}:8080` | (string & {});
};

/**
 * Account schema
 */
export type Account = {
    accountCode?: string;
    accountName?: string;
    accountSubType?: string;
    accountType?: string;
    description?: string;
    hotelId?: number;
    id?: number;
    isActive?: boolean;
    isSystem?: boolean;
    normalBalance?: string;
    parentId?: number;
};

/**
 * Expense schema
 */
export type Expense = {
    accountId?: number;
    amount?: number;
    category?: string;
    createdBy?: number;
    description?: string;
    expenseDate?: string;
    hotelId?: number;
    id?: number;
    notes?: string;
    paymentMethod?: string;
    paymentStatus?: string;
    reference?: string;
    vendor?: string;
};

/**
 * Guest schema
 */
export type Guest = {
    address?: string;
    dateOfBirth?: string;
    fatherName?: string;
    firstName: string;
    gender?: string;
    hotelId?: number;
    id?: number;
    idNumber?: string;
    lastName?: string;
    nationalId?: string;
    nationality?: string;
    occupation?: string;
    phone?: string;
    placeOfBirth?: string;
    postalCode?: string;
    reservations?: Array<{
        breakfast?: boolean;
        departureDate?: string;
        destination?: string;
        durationOfStay?: number;
        entryDate?: string;
        guestId?: number;
        guide?: boolean;
        hotelId?: string;
        id?: number;
        notes?: string;
        numberOfPeople?: number;
        origin?: string;
        payment?: {
            agency?: boolean;
            contractType?: string;
            id?: number;
            isCash?: boolean;
            referrer?: string;
            reservationId?: number;
        };
        purposeOfTravel?: string;
        reservationCode?: string;
        roomPrice?: number;
        rooms?: Array<{
            amenities?: Array<{
                hotelId?: string;
                id?: number;
                name?: string;
                translation?: {
                    [key: string]: string;
                };
            }>;
            basePrice?: number;
            capacity?: number;
            description?: string;
            floor?: number;
            hotelId?: number;
            id?: number;
            name?: string;
            roomNumber: string;
            roomType?: {
                colorHex?: string;
                hotelId?: number;
                id?: number;
                name?: string;
                translation?: {
                    [key: string]: string;
                };
            };
            roomTypeId?: number;
            status?: {
                colorHex?: string;
                hotelId?: number;
                id?: number;
                name?: string;
                translation?: {
                    [key: string]: string;
                };
            };
            statusId?: number;
        }>;
        userCheckIn?: string;
        userCheckOut?: string;
    }>;
};

/**
 * GuestSettlementResponse schema
 */
export type GuestSettlementResponse = {
    balance?: number;
    parkingTransactions?: Array<{
        amountDue?: number;
        amountPaid?: number;
        entryTime?: string;
        exitTime?: string;
        hoursParked?: number;
        id?: number;
        licensePlate?: string;
        rateApplied?: number;
        status?: string;
    }>;
    reservations?: Array<{
        checkInDate?: string;
        checkOutDate?: string;
        id?: number;
        paidAmount?: number;
        reservationCode?: string;
        roomPrice?: number;
        status?: string;
    }>;
    totalDue?: number;
    totalPaid?: number;
    totalParking?: number;
    totalRoom?: number;
};

/**
 * GuestWithReservationRequest schema
 */
export type GuestWithReservationRequest = {
    guest?: {
        address?: string;
        dateOfBirth?: string;
        fatherName?: string;
        firstName: string;
        gender?: string;
        hotelId?: number;
        id?: number;
        idNumber?: string;
        lastName?: string;
        nationalId?: string;
        nationality?: string;
        occupation?: string;
        phone?: string;
        placeOfBirth?: string;
        postalCode?: string;
        reservations?: Array<{
            breakfast?: boolean;
            departureDate?: string;
            destination?: string;
            durationOfStay?: number;
            entryDate?: string;
            guestId?: number;
            guide?: boolean;
            hotelId?: string;
            id?: number;
            notes?: string;
            numberOfPeople?: number;
            origin?: string;
            payment?: {
                agency?: boolean;
                contractType?: string;
                id?: number;
                isCash?: boolean;
                referrer?: string;
                reservationId?: number;
            };
            purposeOfTravel?: string;
            reservationCode?: string;
            roomPrice?: number;
            rooms?: Array<{
                amenities?: Array<{
                    hotelId?: string;
                    id?: number;
                    name?: string;
                    translation?: {
                        [key: string]: string;
                    };
                }>;
                basePrice?: number;
                capacity?: number;
                description?: string;
                floor?: number;
                hotelId?: number;
                id?: number;
                name?: string;
                roomNumber: string;
                roomType?: {
                    colorHex?: string;
                    hotelId?: number;
                    id?: number;
                    name?: string;
                    translation?: {
                        [key: string]: string;
                    };
                };
                roomTypeId?: number;
                status?: {
                    colorHex?: string;
                    hotelId?: number;
                    id?: number;
                    name?: string;
                    translation?: {
                        [key: string]: string;
                    };
                };
                statusId?: number;
            }>;
            userCheckIn?: string;
            userCheckOut?: string;
        }>;
    };
    payment?: {
        agency?: boolean;
        contractType?: string;
        isCash?: boolean;
        referrer?: string;
    };
    reservation?: {
        breakfast?: boolean;
        departureDate?: string;
        destination?: string;
        durationOfStay?: number;
        entryDate?: string;
        guide?: boolean;
        notes?: string;
        numberOfPeople?: number;
        origin?: string;
        purposeOfTravel?: string;
        reservationCode?: string;
        roomPrice?: number;
        rooms?: Array<{
            amenities?: Array<{
                hotelId?: string;
                id?: number;
                name?: string;
                translation?: {
                    [key: string]: string;
                };
            }>;
            basePrice?: number;
            capacity?: number;
            description?: string;
            floor?: number;
            hotelId?: number;
            id?: number;
            name?: string;
            roomNumber: string;
            roomType?: {
                colorHex?: string;
                hotelId?: number;
                id?: number;
                name?: string;
                translation?: {
                    [key: string]: string;
                };
            };
            roomTypeId?: number;
            status?: {
                colorHex?: string;
                hotelId?: number;
                id?: number;
                name?: string;
                translation?: {
                    [key: string]: string;
                };
            };
            statusId?: number;
        }>;
    };
};

/**
 * GuestWithReservationResponse schema
 */
export type GuestWithReservationResponse = {
    guest?: {
        address?: string;
        dateOfBirth?: string;
        fatherName?: string;
        firstName: string;
        gender?: string;
        hotelId?: number;
        id?: number;
        idNumber?: string;
        lastName?: string;
        nationalId?: string;
        nationality?: string;
        occupation?: string;
        phone?: string;
        placeOfBirth?: string;
        postalCode?: string;
        reservations?: Array<{
            breakfast?: boolean;
            departureDate?: string;
            destination?: string;
            durationOfStay?: number;
            entryDate?: string;
            guestId?: number;
            guide?: boolean;
            hotelId?: string;
            id?: number;
            notes?: string;
            numberOfPeople?: number;
            origin?: string;
            payment?: {
                agency?: boolean;
                contractType?: string;
                id?: number;
                isCash?: boolean;
                referrer?: string;
                reservationId?: number;
            };
            purposeOfTravel?: string;
            reservationCode?: string;
            roomPrice?: number;
            rooms?: Array<{
                amenities?: Array<{
                    hotelId?: string;
                    id?: number;
                    name?: string;
                    translation?: {
                        [key: string]: string;
                    };
                }>;
                basePrice?: number;
                capacity?: number;
                description?: string;
                floor?: number;
                hotelId?: number;
                id?: number;
                name?: string;
                roomNumber: string;
                roomType?: {
                    colorHex?: string;
                    hotelId?: number;
                    id?: number;
                    name?: string;
                    translation?: {
                        [key: string]: string;
                    };
                };
                roomTypeId?: number;
                status?: {
                    colorHex?: string;
                    hotelId?: number;
                    id?: number;
                    name?: string;
                    translation?: {
                        [key: string]: string;
                    };
                };
                statusId?: number;
            }>;
            userCheckIn?: string;
            userCheckOut?: string;
        }>;
    };
    payment?: {
        agency?: boolean;
        contractType?: string;
        id?: number;
        isCash?: boolean;
        referrer?: string;
        reservationId?: number;
    };
    reservation?: {
        breakfast?: boolean;
        departureDate?: string;
        destination?: string;
        durationOfStay?: number;
        entryDate?: string;
        guestId?: number;
        guide?: boolean;
        hotelId?: string;
        id?: number;
        notes?: string;
        numberOfPeople?: number;
        origin?: string;
        payment?: {
            agency?: boolean;
            contractType?: string;
            id?: number;
            isCash?: boolean;
            referrer?: string;
            reservationId?: number;
        };
        purposeOfTravel?: string;
        reservationCode?: string;
        roomPrice?: number;
        rooms?: Array<{
            amenities?: Array<{
                hotelId?: string;
                id?: number;
                name?: string;
                translation?: {
                    [key: string]: string;
                };
            }>;
            basePrice?: number;
            capacity?: number;
            description?: string;
            floor?: number;
            hotelId?: number;
            id?: number;
            name?: string;
            roomNumber: string;
            roomType?: {
                colorHex?: string;
                hotelId?: number;
                id?: number;
                name?: string;
                translation?: {
                    [key: string]: string;
                };
            };
            roomTypeId?: number;
            status?: {
                colorHex?: string;
                hotelId?: number;
                id?: number;
                name?: string;
                translation?: {
                    [key: string]: string;
                };
            };
            statusId?: number;
        }>;
        userCheckIn?: string;
        userCheckOut?: string;
    };
};

/**
 * HTTPError schema
 */
export type HttpError = {
    /**
     * Human readable error message
     */
    detail?: string;
    errors?: Array<{
        /**
         * Additional information about the error
         */
        more?: {
            [key: string]: unknown;
        };
        /**
         * For example, name of the parameter that caused the error
         */
        name?: string;
        /**
         * Human readable error message
         */
        reason?: string;
    }>;
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * Short title of the error
     */
    title?: string;
    /**
     * URL of the error type. Can be used to lookup the error in a documentation
     */
    type?: string;
};

/**
 * Hotel schema
 */
export type Hotel = {
    address?: string;
    email?: string;
    id?: string;
    name?: string;
    phone?: string;
};

/**
 * Income schema
 */
export type Income = {
    accountId?: number;
    amount?: number;
    category?: string;
    createdBy?: number;
    description?: string;
    hotelId?: number;
    id?: number;
    incomeDate?: string;
    notes?: string;
    paymentMethod?: string;
    paymentStatus?: string;
    reference?: string;
    reservationId?: number;
    source?: string;
};

/**
 * MeResponse schema
 */
export type MeResponse = {
    hotelId?: string;
    permissions?: Array<{
        action?: string;
        category?: string;
        granted?: boolean;
        label?: string;
        page?: string;
        permissionId?: number;
    }>;
    user?: {
        email?: string;
        firstName?: string;
        id?: number;
        lastName?: string;
        userHotels?: Array<{
            hotel?: {
                address?: string;
                email?: string;
                id?: string;
                name?: string;
                phone?: string;
            };
            hotelId?: string;
            role?: {
                hotelId?: string;
                id?: number;
                name?: string;
                translation?: {
                    [key: string]: string;
                };
            };
            roleId?: number;
        }>;
    };
};

/**
 * PaginatedResponse_models.Account schema
 */
export type PaginatedResponseModelsAccount = {
    data?: Array<{
        accountCode?: string;
        accountName?: string;
        accountSubType?: string;
        accountType?: string;
        description?: string;
        hotelId?: number;
        id?: number;
        isActive?: boolean;
        isSystem?: boolean;
        normalBalance?: string;
        parentId?: number;
    }>;
    limit?: number;
    page?: number;
    total?: number;
    totalPages?: number;
};

/**
 * PaginatedResponse_models.Amenity schema
 */
export type PaginatedResponseModelsAmenity = {
    data?: Array<{
        hotelId?: string;
        id?: number;
        name?: string;
        translation?: {
            [key: string]: string;
        };
    }>;
    limit?: number;
    page?: number;
    total?: number;
    totalPages?: number;
};

/**
 * PaginatedResponse_models.Expense schema
 */
export type PaginatedResponseModelsExpense = {
    data?: Array<{
        accountId?: number;
        amount?: number;
        category?: string;
        createdBy?: number;
        description?: string;
        expenseDate?: string;
        hotelId?: number;
        id?: number;
        notes?: string;
        paymentMethod?: string;
        paymentStatus?: string;
        reference?: string;
        vendor?: string;
    }>;
    limit?: number;
    page?: number;
    total?: number;
    totalPages?: number;
};

/**
 * PaginatedResponse_models.Guest schema
 */
export type PaginatedResponseModelsGuest = {
    data?: Array<{
        address?: string;
        dateOfBirth?: string;
        fatherName?: string;
        firstName: string;
        gender?: string;
        hotelId?: number;
        id?: number;
        idNumber?: string;
        lastName?: string;
        nationalId?: string;
        nationality?: string;
        occupation?: string;
        phone?: string;
        placeOfBirth?: string;
        postalCode?: string;
        reservations?: Array<{
            breakfast?: boolean;
            departureDate?: string;
            destination?: string;
            durationOfStay?: number;
            entryDate?: string;
            guestId?: number;
            guide?: boolean;
            hotelId?: string;
            id?: number;
            notes?: string;
            numberOfPeople?: number;
            origin?: string;
            payment?: {
                agency?: boolean;
                contractType?: string;
                id?: number;
                isCash?: boolean;
                referrer?: string;
                reservationId?: number;
            };
            purposeOfTravel?: string;
            reservationCode?: string;
            roomPrice?: number;
            rooms?: Array<{
                amenities?: Array<{
                    hotelId?: string;
                    id?: number;
                    name?: string;
                    translation?: {
                        [key: string]: string;
                    };
                }>;
                basePrice?: number;
                capacity?: number;
                description?: string;
                floor?: number;
                hotelId?: number;
                id?: number;
                name?: string;
                roomNumber: string;
                roomType?: {
                    colorHex?: string;
                    hotelId?: number;
                    id?: number;
                    name?: string;
                    translation?: {
                        [key: string]: string;
                    };
                };
                roomTypeId?: number;
                status?: {
                    colorHex?: string;
                    hotelId?: number;
                    id?: number;
                    name?: string;
                    translation?: {
                        [key: string]: string;
                    };
                };
                statusId?: number;
            }>;
            userCheckIn?: string;
            userCheckOut?: string;
        }>;
    }>;
    limit?: number;
    page?: number;
    total?: number;
    totalPages?: number;
};

/**
 * PaginatedResponse_models.Hotel schema
 */
export type PaginatedResponseModelsHotel = {
    data?: Array<{
        address?: string;
        email?: string;
        id?: string;
        name?: string;
        phone?: string;
    }>;
    limit?: number;
    page?: number;
    total?: number;
    totalPages?: number;
};

/**
 * PaginatedResponse_models.Income schema
 */
export type PaginatedResponseModelsIncome = {
    data?: Array<{
        accountId?: number;
        amount?: number;
        category?: string;
        createdBy?: number;
        description?: string;
        hotelId?: number;
        id?: number;
        incomeDate?: string;
        notes?: string;
        paymentMethod?: string;
        paymentStatus?: string;
        reference?: string;
        reservationId?: number;
        source?: string;
    }>;
    limit?: number;
    page?: number;
    total?: number;
    totalPages?: number;
};

/**
 * PaginatedResponse_models.ParkingLot schema
 */
export type PaginatedResponseModelsParkingLot = {
    data?: Array<{
        dailyRate?: number;
        description?: string;
        hotelId?: number;
        hourlyRate?: number;
        id?: number;
        location?: string;
        name?: string;
        status?: string;
        totalSpots?: number;
    }>;
    limit?: number;
    page?: number;
    total?: number;
    totalPages?: number;
};

/**
 * PaginatedResponse_models.ParkingSpot schema
 */
export type PaginatedResponseModelsParkingSpot = {
    data?: Array<{
        description?: string;
        floor?: string;
        id?: number;
        isCovered?: boolean;
        lotId?: number;
        spotNumber?: string;
        spotType?: string;
        status?: string;
    }>;
    limit?: number;
    page?: number;
    total?: number;
    totalPages?: number;
};

/**
 * PaginatedResponse_models.ParkingSpotStatus schema
 */
export type PaginatedResponseModelsParkingSpotStatus = {
    data?: Array<{
        hotelId?: string;
        id?: number;
        name?: string;
        translation?: {
            [key: string]: string;
        };
    }>;
    limit?: number;
    page?: number;
    total?: number;
    totalPages?: number;
};

/**
 * PaginatedResponse_models.ParkingSpotType schema
 */
export type PaginatedResponseModelsParkingSpotType = {
    data?: Array<{
        hotelId?: string;
        id?: number;
        name?: string;
        translation?: {
            [key: string]: string;
        };
    }>;
    limit?: number;
    page?: number;
    total?: number;
    totalPages?: number;
};

/**
 * PaginatedResponse_models.ParkingTransaction schema
 */
export type PaginatedResponseModelsParkingTransaction = {
    data?: Array<{
        amountDue?: number;
        amountPaid?: number;
        entryTime?: string;
        exitTime?: string;
        guestId?: number;
        hoursParked?: number;
        id?: number;
        licensePlate?: string;
        lotId?: number;
        notes?: string;
        paymentMethod?: string;
        paymentStatus?: string;
        rateApplied?: number;
        reservationId?: number;
        spotId?: number;
        status?: string;
    }>;
    limit?: number;
    page?: number;
    total?: number;
    totalPages?: number;
};

/**
 * PaginatedResponse_models.Reservation schema
 */
export type PaginatedResponseModelsReservation = {
    data?: Array<{
        breakfast?: boolean;
        departureDate?: string;
        destination?: string;
        durationOfStay?: number;
        entryDate?: string;
        guestId?: number;
        guide?: boolean;
        hotelId?: string;
        id?: number;
        notes?: string;
        numberOfPeople?: number;
        origin?: string;
        payment?: {
            agency?: boolean;
            contractType?: string;
            id?: number;
            isCash?: boolean;
            referrer?: string;
            reservationId?: number;
        };
        purposeOfTravel?: string;
        reservationCode?: string;
        roomPrice?: number;
        rooms?: Array<{
            amenities?: Array<{
                hotelId?: string;
                id?: number;
                name?: string;
                translation?: {
                    [key: string]: string;
                };
            }>;
            basePrice?: number;
            capacity?: number;
            description?: string;
            floor?: number;
            hotelId?: number;
            id?: number;
            name?: string;
            roomNumber: string;
            roomType?: {
                colorHex?: string;
                hotelId?: number;
                id?: number;
                name?: string;
                translation?: {
                    [key: string]: string;
                };
            };
            roomTypeId?: number;
            status?: {
                colorHex?: string;
                hotelId?: number;
                id?: number;
                name?: string;
                translation?: {
                    [key: string]: string;
                };
            };
            statusId?: number;
        }>;
        userCheckIn?: string;
        userCheckOut?: string;
    }>;
    limit?: number;
    page?: number;
    total?: number;
    totalPages?: number;
};

/**
 * PaginatedResponse_models.Room schema
 */
export type PaginatedResponseModelsRoom = {
    data?: Array<{
        amenities?: Array<{
            hotelId?: string;
            id?: number;
            name?: string;
            translation?: {
                [key: string]: string;
            };
        }>;
        basePrice?: number;
        capacity?: number;
        description?: string;
        floor?: number;
        hotelId?: number;
        id?: number;
        name?: string;
        roomNumber: string;
        roomType?: {
            colorHex?: string;
            hotelId?: number;
            id?: number;
            name?: string;
            translation?: {
                [key: string]: string;
            };
        };
        roomTypeId?: number;
        status?: {
            colorHex?: string;
            hotelId?: number;
            id?: number;
            name?: string;
            translation?: {
                [key: string]: string;
            };
        };
        statusId?: number;
    }>;
    limit?: number;
    page?: number;
    total?: number;
    totalPages?: number;
};

/**
 * PaginatedResponse_models.RoomStatus schema
 */
export type PaginatedResponseModelsRoomStatus = {
    data?: Array<{
        colorHex?: string;
        hotelId?: number;
        id?: number;
        name?: string;
        translation?: {
            [key: string]: string;
        };
    }>;
    limit?: number;
    page?: number;
    total?: number;
    totalPages?: number;
};

/**
 * PaginatedResponse_models.RoomType schema
 */
export type PaginatedResponseModelsRoomType = {
    data?: Array<{
        colorHex?: string;
        hotelId?: number;
        id?: number;
        name?: string;
        translation?: {
            [key: string]: string;
        };
    }>;
    limit?: number;
    page?: number;
    total?: number;
    totalPages?: number;
};

/**
 * PaginatedResponse_models.SanitizedUser schema
 */
export type PaginatedResponseModelsSanitizedUser = {
    data?: Array<{
        email?: string;
        firstName?: string;
        id?: number;
        lastName?: string;
        userHotels?: Array<{
            hotel?: {
                address?: string;
                email?: string;
                id?: string;
                name?: string;
                phone?: string;
            };
            hotelId?: string;
            role?: {
                hotelId?: string;
                id?: number;
                name?: string;
                translation?: {
                    [key: string]: string;
                };
            };
            roleId?: number;
        }>;
    }>;
    limit?: number;
    page?: number;
    total?: number;
    totalPages?: number;
};

/**
 * PaginatedResponse_models.Vehicle schema
 */
export type PaginatedResponseModelsVehicle = {
    data?: Array<{
        color?: string;
        guestId?: number;
        id?: number;
        isRegistered?: boolean;
        licensePlate?: string;
        make?: string;
        model?: string;
        notes?: string;
        vehicleType?: string;
    }>;
    limit?: number;
    page?: number;
    total?: number;
    totalPages?: number;
};

/**
 * ParkingLot schema
 */
export type ParkingLot = {
    dailyRate?: number;
    description?: string;
    hotelId?: number;
    hourlyRate?: number;
    id?: number;
    location?: string;
    name?: string;
    status?: string;
    totalSpots?: number;
};

/**
 * ParkingSpot schema
 */
export type ParkingSpot = {
    description?: string;
    floor?: string;
    id?: number;
    isCovered?: boolean;
    lotId?: number;
    spotNumber?: string;
    spotType?: string;
    status?: string;
};

/**
 * ParkingStats schema
 */
export type ParkingStats = {
    availableSpots?: number;
    lots?: number;
    spots?: number;
};

/**
 * ParkingTransaction schema
 */
export type ParkingTransaction = {
    amountDue?: number;
    amountPaid?: number;
    entryTime?: string;
    exitTime?: string;
    guestId?: number;
    hoursParked?: number;
    id?: number;
    licensePlate?: string;
    lotId?: number;
    notes?: string;
    paymentMethod?: string;
    paymentStatus?: string;
    rateApplied?: number;
    reservationId?: number;
    spotId?: number;
    status?: string;
};

/**
 * Reservation schema
 */
export type Reservation = {
    breakfast?: boolean;
    departureDate?: string;
    destination?: string;
    durationOfStay?: number;
    entryDate?: string;
    guestId?: number;
    guide?: boolean;
    hotelId?: string;
    id?: number;
    notes?: string;
    numberOfPeople?: number;
    origin?: string;
    payment?: {
        agency?: boolean;
        contractType?: string;
        id?: number;
        isCash?: boolean;
        referrer?: string;
        reservationId?: number;
    };
    purposeOfTravel?: string;
    reservationCode?: string;
    roomPrice?: number;
    rooms?: Array<{
        amenities?: Array<{
            hotelId?: string;
            id?: number;
            name?: string;
            translation?: {
                [key: string]: string;
            };
        }>;
        basePrice?: number;
        capacity?: number;
        description?: string;
        floor?: number;
        hotelId?: number;
        id?: number;
        name?: string;
        roomNumber: string;
        roomType?: {
            colorHex?: string;
            hotelId?: number;
            id?: number;
            name?: string;
            translation?: {
                [key: string]: string;
            };
        };
        roomTypeId?: number;
        status?: {
            colorHex?: string;
            hotelId?: number;
            id?: number;
            name?: string;
            translation?: {
                [key: string]: string;
            };
        };
        statusId?: number;
    }>;
    userCheckIn?: string;
    userCheckOut?: string;
};

/**
 * Room schema
 */
export type Room = {
    amenities?: Array<{
        hotelId?: string;
        id?: number;
        name?: string;
        translation?: {
            [key: string]: string;
        };
    }>;
    basePrice?: number;
    capacity?: number;
    description?: string;
    floor?: number;
    hotelId?: number;
    id?: number;
    name?: string;
    roomNumber: string;
    roomType?: {
        colorHex?: string;
        hotelId?: number;
        id?: number;
        name?: string;
        translation?: {
            [key: string]: string;
        };
    };
    roomTypeId?: number;
    status?: {
        colorHex?: string;
        hotelId?: number;
        id?: number;
        name?: string;
        translation?: {
            [key: string]: string;
        };
    };
    statusId?: number;
};

/**
 * SettleGuestRequest schema
 */
export type SettleGuestRequest = {
    amount?: number;
    notes?: string;
    parkingTxnIds?: Array<number>;
    paymentMethod?: string;
    reference?: string;
    reservationIds?: Array<number>;
};

/**
 * Vehicle schema
 */
export type Vehicle = {
    color?: string;
    guestId?: number;
    id?: number;
    isRegistered?: boolean;
    licensePlate?: string;
    make?: string;
    model?: string;
    notes?: string;
    vehicleType?: string;
};

/**
 * bool schema
 */
export type Bool = boolean;

/**
 * loginDto schema
 */
export type LoginDto = {
    email?: string;
    password?: string;
};

/**
 * loginResponse schema
 */
export type LoginResponse = {
    hotelId?: string;
    permissions?: Array<{
        action?: string;
        category?: string;
        granted?: boolean;
        label?: string;
        page?: string;
        permissionId?: number;
    }>;
    user?: {
        email?: string;
        firstName?: string;
        id?: number;
        lastName?: string;
        userHotels?: Array<{
            hotel?: {
                address?: string;
                email?: string;
                id?: string;
                name?: string;
                phone?: string;
            };
            hotelId?: string;
            role?: {
                hotelId?: string;
                id?: number;
                name?: string;
                translation?: {
                    [key: string]: string;
                };
            };
            roleId?: number;
        }>;
    };
};

/**
 * okResponse schema
 */
export type OkResponse = unknown;

/**
 * permissionsResponse schema
 */
export type PermissionsResponse = {
    data?: Array<{
        action?: string;
        category?: string;
        hotelId?: string;
        id?: number;
        label?: string;
        page?: string;
    }>;
};

/**
 * setPermissionDto schema
 */
export type SetPermissionDto = {
    granted?: boolean;
};

/**
 * string schema
 */
export type String = string;

/**
 * templatesResponse schema
 */
export type TemplatesResponse = {
    data?: Array<{
        description?: string;
        id?: number;
        name?: string;
        permissions?: Array<{
            action?: string;
            category?: string;
            hotelId?: string;
            id?: number;
            label?: string;
            page?: string;
        }>;
    }>;
};

/**
 * unknown-interface schema
 */
export type UnknownInterface = unknown;

/**
 * userCreateDto schema
 */
export type UserCreateDto = {
    email?: string;
    firstName?: string;
    lastName?: string;
    password?: string;
};

/**
 * userCreateResponse schema
 */
export type UserCreateResponse = unknown;

/**
 * userPermissionsResponse schema
 */
export type UserPermissionsResponse = {
    permissions?: Array<{
        action?: string;
        category?: string;
        granted?: boolean;
        label?: string;
        page?: string;
        permissionId?: number;
    }>;
    userId?: number;
};

export type GetApiAccountingAccountsData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: {
        limit?: number;
        page?: number;
    };
    url: '/api/accounting/accounts/';
};

export type GetApiAccountingAccountsErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type GetApiAccountingAccountsError = GetApiAccountingAccountsErrors[keyof GetApiAccountingAccountsErrors];

export type GetApiAccountingAccountsResponses = {
    /**
     * OK
     */
    200: PaginatedResponseModelsAccount;
};

export type GetApiAccountingAccountsResponse = GetApiAccountingAccountsResponses[keyof GetApiAccountingAccountsResponses];

export type PostApiAccountingAccountsData = {
    /**
     * Request body for models.Account
     */
    body: Account;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: never;
    url: '/api/accounting/accounts/';
};

export type PostApiAccountingAccountsErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type PostApiAccountingAccountsError = PostApiAccountingAccountsErrors[keyof PostApiAccountingAccountsErrors];

export type PostApiAccountingAccountsResponses = {
    /**
     * OK
     */
    200: Account;
};

export type PostApiAccountingAccountsResponse = PostApiAccountingAccountsResponses[keyof PostApiAccountingAccountsResponses];

export type GetApiAccountingExpensesData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: {
        limit?: number;
        page?: number;
    };
    url: '/api/accounting/expenses/';
};

export type GetApiAccountingExpensesErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type GetApiAccountingExpensesError = GetApiAccountingExpensesErrors[keyof GetApiAccountingExpensesErrors];

export type GetApiAccountingExpensesResponses = {
    /**
     * OK
     */
    200: PaginatedResponseModelsExpense;
};

export type GetApiAccountingExpensesResponse = GetApiAccountingExpensesResponses[keyof GetApiAccountingExpensesResponses];

export type PostApiAccountingExpensesData = {
    /**
     * Request body for models.Expense
     */
    body: Expense;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: never;
    url: '/api/accounting/expenses/';
};

export type PostApiAccountingExpensesErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type PostApiAccountingExpensesError = PostApiAccountingExpensesErrors[keyof PostApiAccountingExpensesErrors];

export type PostApiAccountingExpensesResponses = {
    /**
     * OK
     */
    200: Expense;
};

export type PostApiAccountingExpensesResponse = PostApiAccountingExpensesResponses[keyof PostApiAccountingExpensesResponses];

export type GetApiAccountingIncomeData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: {
        limit?: number;
        page?: number;
    };
    url: '/api/accounting/income/';
};

export type GetApiAccountingIncomeErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type GetApiAccountingIncomeError = GetApiAccountingIncomeErrors[keyof GetApiAccountingIncomeErrors];

export type GetApiAccountingIncomeResponses = {
    /**
     * OK
     */
    200: PaginatedResponseModelsIncome;
};

export type GetApiAccountingIncomeResponse = GetApiAccountingIncomeResponses[keyof GetApiAccountingIncomeResponses];

export type PostApiAccountingIncomeData = {
    /**
     * Request body for models.Income
     */
    body: Income;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: never;
    url: '/api/accounting/income/';
};

export type PostApiAccountingIncomeErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type PostApiAccountingIncomeError = PostApiAccountingIncomeErrors[keyof PostApiAccountingIncomeErrors];

export type PostApiAccountingIncomeResponses = {
    /**
     * OK
     */
    200: Income;
};

export type PostApiAccountingIncomeResponse = PostApiAccountingIncomeResponses[keyof PostApiAccountingIncomeResponses];

export type PostApiAuthLoginData = {
    /**
     * Request body for auth.loginDto
     */
    body: LoginDto;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type PostApiAuthLoginErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type PostApiAuthLoginError = PostApiAuthLoginErrors[keyof PostApiAuthLoginErrors];

export type PostApiAuthLoginResponses = {
    /**
     * OK
     */
    200: LoginResponse;
};

export type PostApiAuthLoginResponse = PostApiAuthLoginResponses[keyof PostApiAuthLoginResponses];

export type PostApiAuthLogoutData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type PostApiAuthLogoutErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type PostApiAuthLogoutError = PostApiAuthLogoutErrors[keyof PostApiAuthLogoutErrors];

export type PostApiAuthLogoutResponses = {
    /**
     * OK
     */
    200: Bool;
};

export type PostApiAuthLogoutResponse = PostApiAuthLogoutResponses[keyof PostApiAuthLogoutResponses];

export type GetApiAuthMeData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type GetApiAuthMeErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type GetApiAuthMeError = GetApiAuthMeErrors[keyof GetApiAuthMeErrors];

export type GetApiAuthMeResponses = {
    /**
     * OK
     */
    200: MeResponse;
};

export type GetApiAuthMeResponse = GetApiAuthMeResponses[keyof GetApiAuthMeResponses];

export type GetApiGuestsData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: {
        limit?: number;
        page?: number;
    };
    url: '/api/guests/';
};

export type GetApiGuestsErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type GetApiGuestsError = GetApiGuestsErrors[keyof GetApiGuestsErrors];

export type GetApiGuestsResponses = {
    /**
     * OK
     */
    200: PaginatedResponseModelsGuest;
};

export type GetApiGuestsResponse = GetApiGuestsResponses[keyof GetApiGuestsResponses];

export type PostApiGuestsData = {
    /**
     * Request body for models.Guest
     */
    body: Guest;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: never;
    url: '/api/guests/';
};

export type PostApiGuestsErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type PostApiGuestsError = PostApiGuestsErrors[keyof PostApiGuestsErrors];

export type PostApiGuestsResponses = {
    /**
     * OK
     */
    200: Guest;
};

export type PostApiGuestsResponse = PostApiGuestsResponses[keyof PostApiGuestsResponses];

export type PostApiGuestsWithReservationData = {
    /**
     * Request body for guests.GuestWithReservationRequest
     */
    body: GuestWithReservationRequest;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: never;
    url: '/api/guests/with-reservation';
};

export type PostApiGuestsWithReservationErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type PostApiGuestsWithReservationError = PostApiGuestsWithReservationErrors[keyof PostApiGuestsWithReservationErrors];

export type PostApiGuestsWithReservationResponses = {
    /**
     * OK
     */
    200: GuestWithReservationResponse;
};

export type PostApiGuestsWithReservationResponse = PostApiGuestsWithReservationResponses[keyof PostApiGuestsWithReservationResponses];

export type GetApiGuestsIdData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/guests/{id}';
};

export type GetApiGuestsIdErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type GetApiGuestsIdError = GetApiGuestsIdErrors[keyof GetApiGuestsIdErrors];

export type GetApiGuestsIdResponses = {
    /**
     * OK
     */
    200: Guest;
};

export type GetApiGuestsIdResponse = GetApiGuestsIdResponses[keyof GetApiGuestsIdResponses];

export type PutApiGuestsIdData = {
    /**
     * Request body for models.Guest
     */
    body: Guest;
    headers?: {
        Accept?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/guests/{id}';
};

export type PutApiGuestsIdErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type PutApiGuestsIdError = PutApiGuestsIdErrors[keyof PutApiGuestsIdErrors];

export type PutApiGuestsIdResponses = {
    /**
     * OK
     */
    200: Guest;
};

export type PutApiGuestsIdResponse = PutApiGuestsIdResponses[keyof PutApiGuestsIdResponses];

export type GetApiGuestsIdSettleData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/guests/{id}/settle';
};

export type GetApiGuestsIdSettleErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type GetApiGuestsIdSettleError = GetApiGuestsIdSettleErrors[keyof GetApiGuestsIdSettleErrors];

export type GetApiGuestsIdSettleResponses = {
    /**
     * OK
     */
    200: GuestSettlementResponse;
};

export type GetApiGuestsIdSettleResponse = GetApiGuestsIdSettleResponses[keyof GetApiGuestsIdSettleResponses];

export type PostApiGuestsIdSettleData = {
    /**
     * Request body for guests.SettleGuestRequest
     */
    body: SettleGuestRequest;
    headers?: {
        Accept?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/guests/{id}/settle';
};

export type PostApiGuestsIdSettleErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type PostApiGuestsIdSettleError = PostApiGuestsIdSettleErrors[keyof PostApiGuestsIdSettleErrors];

export type PostApiGuestsIdSettleResponses = {
    /**
     * OK
     */
    200: OkResponse;
};

export type PostApiGuestsIdSettleResponse = PostApiGuestsIdSettleResponses[keyof PostApiGuestsIdSettleResponses];

export type GetApiHealthzData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: never;
    url: '/api/healthz';
};

export type GetApiHealthzErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type GetApiHealthzError = GetApiHealthzErrors[keyof GetApiHealthzErrors];

export type GetApiHealthzResponses = {
    /**
     * OK
     */
    200: String;
};

export type GetApiHealthzResponse = GetApiHealthzResponses[keyof GetApiHealthzResponses];

export type GetApiHotelsData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: {
        limit?: number;
        page?: number;
    };
    url: '/api/hotels/';
};

export type GetApiHotelsErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type GetApiHotelsError = GetApiHotelsErrors[keyof GetApiHotelsErrors];

export type GetApiHotelsResponses = {
    /**
     * OK
     */
    200: PaginatedResponseModelsHotel;
};

export type GetApiHotelsResponse = GetApiHotelsResponses[keyof GetApiHotelsResponses];

export type PostApiHotelsData = {
    /**
     * Request body for models.Hotel
     */
    body: Hotel;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: never;
    url: '/api/hotels/';
};

export type PostApiHotelsErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type PostApiHotelsError = PostApiHotelsErrors[keyof PostApiHotelsErrors];

export type PostApiHotelsResponses = {
    /**
     * OK
     */
    200: Hotel;
};

export type PostApiHotelsResponse = PostApiHotelsResponses[keyof PostApiHotelsResponses];

export type DeleteApiHotelsIdData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/hotels/{id}';
};

export type DeleteApiHotelsIdErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type DeleteApiHotelsIdError = DeleteApiHotelsIdErrors[keyof DeleteApiHotelsIdErrors];

export type DeleteApiHotelsIdResponses = {
    /**
     * OK
     */
    200: OkResponse;
};

export type DeleteApiHotelsIdResponse = DeleteApiHotelsIdResponses[keyof DeleteApiHotelsIdResponses];

export type GetApiHotelsIdData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/hotels/{id}';
};

export type GetApiHotelsIdErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type GetApiHotelsIdError = GetApiHotelsIdErrors[keyof GetApiHotelsIdErrors];

export type GetApiHotelsIdResponses = {
    /**
     * OK
     */
    200: Hotel;
};

export type GetApiHotelsIdResponse = GetApiHotelsIdResponses[keyof GetApiHotelsIdResponses];

export type PutApiHotelsIdData = {
    /**
     * Request body for models.Hotel
     */
    body: Hotel;
    headers?: {
        Accept?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/hotels/{id}';
};

export type PutApiHotelsIdErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type PutApiHotelsIdError = PutApiHotelsIdErrors[keyof PutApiHotelsIdErrors];

export type PutApiHotelsIdResponses = {
    /**
     * OK
     */
    200: Hotel;
};

export type PutApiHotelsIdResponse = PutApiHotelsIdResponses[keyof PutApiHotelsIdResponses];

export type GetApiParkingLotsData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: {
        limit?: number;
        page?: number;
    };
    url: '/api/parking/lots/';
};

export type GetApiParkingLotsErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type GetApiParkingLotsError = GetApiParkingLotsErrors[keyof GetApiParkingLotsErrors];

export type GetApiParkingLotsResponses = {
    /**
     * OK
     */
    200: PaginatedResponseModelsParkingLot;
};

export type GetApiParkingLotsResponse = GetApiParkingLotsResponses[keyof GetApiParkingLotsResponses];

export type PostApiParkingLotsData = {
    /**
     * Request body for models.ParkingLot
     */
    body: ParkingLot;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: never;
    url: '/api/parking/lots/';
};

export type PostApiParkingLotsErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type PostApiParkingLotsError = PostApiParkingLotsErrors[keyof PostApiParkingLotsErrors];

export type PostApiParkingLotsResponses = {
    /**
     * OK
     */
    200: ParkingLot;
};

export type PostApiParkingLotsResponse = PostApiParkingLotsResponses[keyof PostApiParkingLotsResponses];

export type DeleteApiParkingLotsIdData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/parking/lots/{id}';
};

export type DeleteApiParkingLotsIdErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type DeleteApiParkingLotsIdError = DeleteApiParkingLotsIdErrors[keyof DeleteApiParkingLotsIdErrors];

export type DeleteApiParkingLotsIdResponses = {
    /**
     * OK
     */
    200: OkResponse;
};

export type DeleteApiParkingLotsIdResponse = DeleteApiParkingLotsIdResponses[keyof DeleteApiParkingLotsIdResponses];

export type GetApiParkingLotsIdData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/parking/lots/{id}';
};

export type GetApiParkingLotsIdErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type GetApiParkingLotsIdError = GetApiParkingLotsIdErrors[keyof GetApiParkingLotsIdErrors];

export type GetApiParkingLotsIdResponses = {
    /**
     * OK
     */
    200: ParkingLot;
};

export type GetApiParkingLotsIdResponse = GetApiParkingLotsIdResponses[keyof GetApiParkingLotsIdResponses];

export type PutApiParkingLotsIdData = {
    /**
     * Request body for models.ParkingLot
     */
    body: ParkingLot;
    headers?: {
        Accept?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/parking/lots/{id}';
};

export type PutApiParkingLotsIdErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type PutApiParkingLotsIdError = PutApiParkingLotsIdErrors[keyof PutApiParkingLotsIdErrors];

export type PutApiParkingLotsIdResponses = {
    /**
     * OK
     */
    200: ParkingLot;
};

export type PutApiParkingLotsIdResponse = PutApiParkingLotsIdResponses[keyof PutApiParkingLotsIdResponses];

export type GetApiParkingSpotsData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: {
        limit?: number;
        page?: number;
    };
    url: '/api/parking/spots/';
};

export type GetApiParkingSpotsErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type GetApiParkingSpotsError = GetApiParkingSpotsErrors[keyof GetApiParkingSpotsErrors];

export type GetApiParkingSpotsResponses = {
    /**
     * OK
     */
    200: PaginatedResponseModelsParkingSpot;
};

export type GetApiParkingSpotsResponse = GetApiParkingSpotsResponses[keyof GetApiParkingSpotsResponses];

export type PostApiParkingSpotsData = {
    /**
     * Request body for models.ParkingSpot
     */
    body: ParkingSpot;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: never;
    url: '/api/parking/spots/';
};

export type PostApiParkingSpotsErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type PostApiParkingSpotsError = PostApiParkingSpotsErrors[keyof PostApiParkingSpotsErrors];

export type PostApiParkingSpotsResponses = {
    /**
     * OK
     */
    200: ParkingSpot;
};

export type PostApiParkingSpotsResponse = PostApiParkingSpotsResponses[keyof PostApiParkingSpotsResponses];

export type GetApiParkingSpotsStatusesData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: {
        limit?: number;
        page?: number;
    };
    url: '/api/parking/spots/statuses';
};

export type GetApiParkingSpotsStatusesErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type GetApiParkingSpotsStatusesError = GetApiParkingSpotsStatusesErrors[keyof GetApiParkingSpotsStatusesErrors];

export type GetApiParkingSpotsStatusesResponses = {
    /**
     * OK
     */
    200: PaginatedResponseModelsParkingSpotStatus;
};

export type GetApiParkingSpotsStatusesResponse = GetApiParkingSpotsStatusesResponses[keyof GetApiParkingSpotsStatusesResponses];

export type GetApiParkingSpotsTypesData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: {
        limit?: number;
        page?: number;
    };
    url: '/api/parking/spots/types';
};

export type GetApiParkingSpotsTypesErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type GetApiParkingSpotsTypesError = GetApiParkingSpotsTypesErrors[keyof GetApiParkingSpotsTypesErrors];

export type GetApiParkingSpotsTypesResponses = {
    /**
     * OK
     */
    200: PaginatedResponseModelsParkingSpotType;
};

export type GetApiParkingSpotsTypesResponse = GetApiParkingSpotsTypesResponses[keyof GetApiParkingSpotsTypesResponses];

export type DeleteApiParkingSpotsIdData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/parking/spots/{id}';
};

export type DeleteApiParkingSpotsIdErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type DeleteApiParkingSpotsIdError = DeleteApiParkingSpotsIdErrors[keyof DeleteApiParkingSpotsIdErrors];

export type DeleteApiParkingSpotsIdResponses = {
    /**
     * OK
     */
    200: OkResponse;
};

export type DeleteApiParkingSpotsIdResponse = DeleteApiParkingSpotsIdResponses[keyof DeleteApiParkingSpotsIdResponses];

export type GetApiParkingSpotsIdData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/parking/spots/{id}';
};

export type GetApiParkingSpotsIdErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type GetApiParkingSpotsIdError = GetApiParkingSpotsIdErrors[keyof GetApiParkingSpotsIdErrors];

export type GetApiParkingSpotsIdResponses = {
    /**
     * OK
     */
    200: ParkingSpot;
};

export type GetApiParkingSpotsIdResponse = GetApiParkingSpotsIdResponses[keyof GetApiParkingSpotsIdResponses];

export type PutApiParkingSpotsIdData = {
    /**
     * Request body for models.ParkingSpot
     */
    body: ParkingSpot;
    headers?: {
        Accept?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/parking/spots/{id}';
};

export type PutApiParkingSpotsIdErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type PutApiParkingSpotsIdError = PutApiParkingSpotsIdErrors[keyof PutApiParkingSpotsIdErrors];

export type PutApiParkingSpotsIdResponses = {
    /**
     * OK
     */
    200: ParkingSpot;
};

export type PutApiParkingSpotsIdResponse = PutApiParkingSpotsIdResponses[keyof PutApiParkingSpotsIdResponses];

export type GetApiParkingStatsData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: never;
    url: '/api/parking/stats';
};

export type GetApiParkingStatsErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type GetApiParkingStatsError = GetApiParkingStatsErrors[keyof GetApiParkingStatsErrors];

export type GetApiParkingStatsResponses = {
    /**
     * OK
     */
    200: ParkingStats;
};

export type GetApiParkingStatsResponse = GetApiParkingStatsResponses[keyof GetApiParkingStatsResponses];

export type GetApiParkingTransactionsData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: {
        limit?: number;
        page?: number;
    };
    url: '/api/parking/transactions/';
};

export type GetApiParkingTransactionsErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type GetApiParkingTransactionsError = GetApiParkingTransactionsErrors[keyof GetApiParkingTransactionsErrors];

export type GetApiParkingTransactionsResponses = {
    /**
     * OK
     */
    200: PaginatedResponseModelsParkingTransaction;
};

export type GetApiParkingTransactionsResponse = GetApiParkingTransactionsResponses[keyof GetApiParkingTransactionsResponses];

export type PostApiParkingTransactionsData = {
    /**
     * Request body for models.ParkingTransaction
     */
    body: ParkingTransaction;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: never;
    url: '/api/parking/transactions/';
};

export type PostApiParkingTransactionsErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type PostApiParkingTransactionsError = PostApiParkingTransactionsErrors[keyof PostApiParkingTransactionsErrors];

export type PostApiParkingTransactionsResponses = {
    /**
     * OK
     */
    200: ParkingTransaction;
};

export type PostApiParkingTransactionsResponse = PostApiParkingTransactionsResponses[keyof PostApiParkingTransactionsResponses];

export type GetApiParkingTransactionsIdData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/parking/transactions/{id}';
};

export type GetApiParkingTransactionsIdErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type GetApiParkingTransactionsIdError = GetApiParkingTransactionsIdErrors[keyof GetApiParkingTransactionsIdErrors];

export type GetApiParkingTransactionsIdResponses = {
    /**
     * OK
     */
    200: ParkingTransaction;
};

export type GetApiParkingTransactionsIdResponse = GetApiParkingTransactionsIdResponses[keyof GetApiParkingTransactionsIdResponses];

export type PostApiParkingTransactionsIdCheckOutData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/parking/transactions/{id}/check-out';
};

export type PostApiParkingTransactionsIdCheckOutErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type PostApiParkingTransactionsIdCheckOutError = PostApiParkingTransactionsIdCheckOutErrors[keyof PostApiParkingTransactionsIdCheckOutErrors];

export type PostApiParkingTransactionsIdCheckOutResponses = {
    /**
     * OK
     */
    200: Bool;
};

export type PostApiParkingTransactionsIdCheckOutResponse = PostApiParkingTransactionsIdCheckOutResponses[keyof PostApiParkingTransactionsIdCheckOutResponses];

export type GetApiParkingVehiclesData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: {
        limit?: number;
        page?: number;
    };
    url: '/api/parking/vehicles/';
};

export type GetApiParkingVehiclesErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type GetApiParkingVehiclesError = GetApiParkingVehiclesErrors[keyof GetApiParkingVehiclesErrors];

export type GetApiParkingVehiclesResponses = {
    /**
     * OK
     */
    200: PaginatedResponseModelsVehicle;
};

export type GetApiParkingVehiclesResponse = GetApiParkingVehiclesResponses[keyof GetApiParkingVehiclesResponses];

export type PostApiParkingVehiclesData = {
    /**
     * Request body for models.Vehicle
     */
    body: Vehicle;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: never;
    url: '/api/parking/vehicles/';
};

export type PostApiParkingVehiclesErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type PostApiParkingVehiclesError = PostApiParkingVehiclesErrors[keyof PostApiParkingVehiclesErrors];

export type PostApiParkingVehiclesResponses = {
    /**
     * OK
     */
    200: Vehicle;
};

export type PostApiParkingVehiclesResponse = PostApiParkingVehiclesResponses[keyof PostApiParkingVehiclesResponses];

export type DeleteApiParkingVehiclesIdData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/parking/vehicles/{id}';
};

export type DeleteApiParkingVehiclesIdErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type DeleteApiParkingVehiclesIdError = DeleteApiParkingVehiclesIdErrors[keyof DeleteApiParkingVehiclesIdErrors];

export type DeleteApiParkingVehiclesIdResponses = {
    /**
     * OK
     */
    200: OkResponse;
};

export type DeleteApiParkingVehiclesIdResponse = DeleteApiParkingVehiclesIdResponses[keyof DeleteApiParkingVehiclesIdResponses];

export type GetApiParkingVehiclesIdData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/parking/vehicles/{id}';
};

export type GetApiParkingVehiclesIdErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type GetApiParkingVehiclesIdError = GetApiParkingVehiclesIdErrors[keyof GetApiParkingVehiclesIdErrors];

export type GetApiParkingVehiclesIdResponses = {
    /**
     * OK
     */
    200: Vehicle;
};

export type GetApiParkingVehiclesIdResponse = GetApiParkingVehiclesIdResponses[keyof GetApiParkingVehiclesIdResponses];

export type PutApiParkingVehiclesIdData = {
    /**
     * Request body for models.Vehicle
     */
    body: Vehicle;
    headers?: {
        Accept?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/parking/vehicles/{id}';
};

export type PutApiParkingVehiclesIdErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type PutApiParkingVehiclesIdError = PutApiParkingVehiclesIdErrors[keyof PutApiParkingVehiclesIdErrors];

export type PutApiParkingVehiclesIdResponses = {
    /**
     * OK
     */
    200: Vehicle;
};

export type PutApiParkingVehiclesIdResponse = PutApiParkingVehiclesIdResponses[keyof PutApiParkingVehiclesIdResponses];

export type GetApiPermissionsData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: never;
    url: '/api/permissions/';
};

export type GetApiPermissionsErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type GetApiPermissionsError = GetApiPermissionsErrors[keyof GetApiPermissionsErrors];

export type GetApiPermissionsResponses = {
    /**
     * OK
     */
    200: PermissionsResponse;
};

export type GetApiPermissionsResponse = GetApiPermissionsResponses[keyof GetApiPermissionsResponses];

export type GetApiPermissionsTemplatesData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: never;
    url: '/api/permissions/templates';
};

export type GetApiPermissionsTemplatesErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type GetApiPermissionsTemplatesError = GetApiPermissionsTemplatesErrors[keyof GetApiPermissionsTemplatesErrors];

export type GetApiPermissionsTemplatesResponses = {
    /**
     * OK
     */
    200: TemplatesResponse;
};

export type GetApiPermissionsTemplatesResponse = GetApiPermissionsTemplatesResponses[keyof GetApiPermissionsTemplatesResponses];

export type GetApiPermissionsUserUserIdData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path: {
        userId: string;
    };
    query?: never;
    url: '/api/permissions/user/{userId}';
};

export type GetApiPermissionsUserUserIdErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type GetApiPermissionsUserUserIdError = GetApiPermissionsUserUserIdErrors[keyof GetApiPermissionsUserUserIdErrors];

export type GetApiPermissionsUserUserIdResponses = {
    /**
     * OK
     */
    200: UserPermissionsResponse;
};

export type GetApiPermissionsUserUserIdResponse = GetApiPermissionsUserUserIdResponses[keyof GetApiPermissionsUserUserIdResponses];

export type DeleteApiPermissionsUserUserIdPermissionPermissionIdData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path: {
        userId: string;
        permissionId: string;
    };
    query?: never;
    url: '/api/permissions/user/{userId}/permission/{permissionId}';
};

export type DeleteApiPermissionsUserUserIdPermissionPermissionIdErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type DeleteApiPermissionsUserUserIdPermissionPermissionIdError = DeleteApiPermissionsUserUserIdPermissionPermissionIdErrors[keyof DeleteApiPermissionsUserUserIdPermissionPermissionIdErrors];

export type DeleteApiPermissionsUserUserIdPermissionPermissionIdResponses = {
    /**
     * OK
     */
    200: String;
};

export type DeleteApiPermissionsUserUserIdPermissionPermissionIdResponse = DeleteApiPermissionsUserUserIdPermissionPermissionIdResponses[keyof DeleteApiPermissionsUserUserIdPermissionPermissionIdResponses];

export type PostApiPermissionsUserUserIdTemplateTemplateIdData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path: {
        userId: string;
        templateId: string;
    };
    query?: never;
    url: '/api/permissions/user/{userId}/template/{templateId}';
};

export type PostApiPermissionsUserUserIdTemplateTemplateIdErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type PostApiPermissionsUserUserIdTemplateTemplateIdError = PostApiPermissionsUserUserIdTemplateTemplateIdErrors[keyof PostApiPermissionsUserUserIdTemplateTemplateIdErrors];

export type PostApiPermissionsUserUserIdTemplateTemplateIdResponses = {
    /**
     * OK
     */
    200: String;
};

export type PostApiPermissionsUserUserIdTemplateTemplateIdResponse = PostApiPermissionsUserUserIdTemplateTemplateIdResponses[keyof PostApiPermissionsUserUserIdTemplateTemplateIdResponses];

export type PostApiPermissionsUserUserIdPermissionIdData = {
    /**
     * Request body for permissions.setPermissionDto
     */
    body: SetPermissionDto;
    headers?: {
        Accept?: string;
    };
    path: {
        userId: string;
        permissionId: string;
    };
    query?: never;
    url: '/api/permissions/user/{userId}/{permissionId}';
};

export type PostApiPermissionsUserUserIdPermissionIdErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type PostApiPermissionsUserUserIdPermissionIdError = PostApiPermissionsUserUserIdPermissionIdErrors[keyof PostApiPermissionsUserUserIdPermissionIdErrors];

export type PostApiPermissionsUserUserIdPermissionIdResponses = {
    /**
     * OK
     */
    200: String;
};

export type PostApiPermissionsUserUserIdPermissionIdResponse = PostApiPermissionsUserUserIdPermissionIdResponses[keyof PostApiPermissionsUserUserIdPermissionIdResponses];

export type GetApiReadyzData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: never;
    url: '/api/readyz';
};

export type GetApiReadyzErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type GetApiReadyzError = GetApiReadyzErrors[keyof GetApiReadyzErrors];

export type GetApiReadyzResponses = {
    /**
     * OK
     */
    200: String;
};

export type GetApiReadyzResponse = GetApiReadyzResponses[keyof GetApiReadyzResponses];

export type GetApiReservationData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: {
        limit?: number;
        page?: number;
    };
    url: '/api/reservation/';
};

export type GetApiReservationErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type GetApiReservationError = GetApiReservationErrors[keyof GetApiReservationErrors];

export type GetApiReservationResponses = {
    /**
     * OK
     */
    200: PaginatedResponseModelsReservation;
};

export type GetApiReservationResponse = GetApiReservationResponses[keyof GetApiReservationResponses];

export type PostApiReservationData = {
    /**
     * Request body for models.Reservation
     */
    body: Reservation;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: never;
    url: '/api/reservation/';
};

export type PostApiReservationErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type PostApiReservationError = PostApiReservationErrors[keyof PostApiReservationErrors];

export type PostApiReservationResponses = {
    /**
     * OK
     */
    200: Reservation;
};

export type PostApiReservationResponse = PostApiReservationResponses[keyof PostApiReservationResponses];

export type GetApiReservationIdData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/reservation/{id}';
};

export type GetApiReservationIdErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type GetApiReservationIdError = GetApiReservationIdErrors[keyof GetApiReservationIdErrors];

export type GetApiReservationIdResponses = {
    /**
     * OK
     */
    200: Reservation;
};

export type GetApiReservationIdResponse = GetApiReservationIdResponses[keyof GetApiReservationIdResponses];

export type PutApiReservationIdData = {
    /**
     * Request body for models.Reservation
     */
    body: Reservation;
    headers?: {
        Accept?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/reservation/{id}';
};

export type PutApiReservationIdErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type PutApiReservationIdError = PutApiReservationIdErrors[keyof PutApiReservationIdErrors];

export type PutApiReservationIdResponses = {
    /**
     * OK
     */
    200: Reservation;
};

export type PutApiReservationIdResponse = PutApiReservationIdResponses[keyof PutApiReservationIdResponses];

export type PostApiReservationIdCheckInData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/reservation/{id}/check-in';
};

export type PostApiReservationIdCheckInErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type PostApiReservationIdCheckInError = PostApiReservationIdCheckInErrors[keyof PostApiReservationIdCheckInErrors];

export type PostApiReservationIdCheckInResponses = {
    /**
     * OK
     */
    200: OkResponse;
};

export type PostApiReservationIdCheckInResponse = PostApiReservationIdCheckInResponses[keyof PostApiReservationIdCheckInResponses];

export type PostApiReservationIdCheckOutData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/reservation/{id}/check-out';
};

export type PostApiReservationIdCheckOutErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type PostApiReservationIdCheckOutError = PostApiReservationIdCheckOutErrors[keyof PostApiReservationIdCheckOutErrors];

export type PostApiReservationIdCheckOutResponses = {
    /**
     * OK
     */
    200: OkResponse;
};

export type PostApiReservationIdCheckOutResponse = PostApiReservationIdCheckOutResponses[keyof PostApiReservationIdCheckOutResponses];

export type GetApiRoomsData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: {
        limit?: number;
        page?: number;
    };
    url: '/api/rooms/';
};

export type GetApiRoomsErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type GetApiRoomsError = GetApiRoomsErrors[keyof GetApiRoomsErrors];

export type GetApiRoomsResponses = {
    /**
     * OK
     */
    200: PaginatedResponseModelsRoom;
};

export type GetApiRoomsResponse = GetApiRoomsResponses[keyof GetApiRoomsResponses];

export type PostApiRoomsData = {
    /**
     * Request body for models.Room
     */
    body: Room;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: never;
    url: '/api/rooms/';
};

export type PostApiRoomsErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type PostApiRoomsError = PostApiRoomsErrors[keyof PostApiRoomsErrors];

export type PostApiRoomsResponses = {
    /**
     * OK
     */
    200: Room;
};

export type PostApiRoomsResponse = PostApiRoomsResponses[keyof PostApiRoomsResponses];

export type GetApiRoomsAmenitiesData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: {
        limit?: number;
        page?: number;
    };
    url: '/api/rooms/amenities';
};

export type GetApiRoomsAmenitiesErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type GetApiRoomsAmenitiesError = GetApiRoomsAmenitiesErrors[keyof GetApiRoomsAmenitiesErrors];

export type GetApiRoomsAmenitiesResponses = {
    /**
     * OK
     */
    200: PaginatedResponseModelsAmenity;
};

export type GetApiRoomsAmenitiesResponse = GetApiRoomsAmenitiesResponses[keyof GetApiRoomsAmenitiesResponses];

export type GetApiRoomsStatusesData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: {
        limit?: number;
        page?: number;
    };
    url: '/api/rooms/statuses';
};

export type GetApiRoomsStatusesErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type GetApiRoomsStatusesError = GetApiRoomsStatusesErrors[keyof GetApiRoomsStatusesErrors];

export type GetApiRoomsStatusesResponses = {
    /**
     * OK
     */
    200: PaginatedResponseModelsRoomStatus;
};

export type GetApiRoomsStatusesResponse = GetApiRoomsStatusesResponses[keyof GetApiRoomsStatusesResponses];

export type GetApiRoomsTypesData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: {
        limit?: number;
        page?: number;
    };
    url: '/api/rooms/types';
};

export type GetApiRoomsTypesErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type GetApiRoomsTypesError = GetApiRoomsTypesErrors[keyof GetApiRoomsTypesErrors];

export type GetApiRoomsTypesResponses = {
    /**
     * OK
     */
    200: PaginatedResponseModelsRoomType;
};

export type GetApiRoomsTypesResponse = GetApiRoomsTypesResponses[keyof GetApiRoomsTypesResponses];

export type DeleteApiRoomsIdData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/rooms/{id}';
};

export type DeleteApiRoomsIdErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type DeleteApiRoomsIdError = DeleteApiRoomsIdErrors[keyof DeleteApiRoomsIdErrors];

export type DeleteApiRoomsIdResponses = {
    /**
     * OK
     */
    200: OkResponse;
};

export type DeleteApiRoomsIdResponse = DeleteApiRoomsIdResponses[keyof DeleteApiRoomsIdResponses];

export type GetApiRoomsIdData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/rooms/{id}';
};

export type GetApiRoomsIdErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type GetApiRoomsIdError = GetApiRoomsIdErrors[keyof GetApiRoomsIdErrors];

export type GetApiRoomsIdResponses = {
    /**
     * OK
     */
    200: Room;
};

export type GetApiRoomsIdResponse = GetApiRoomsIdResponses[keyof GetApiRoomsIdResponses];

export type PutApiRoomsIdData = {
    /**
     * Request body for models.Room
     */
    body: Room;
    headers?: {
        Accept?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/rooms/{id}';
};

export type PutApiRoomsIdErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type PutApiRoomsIdError = PutApiRoomsIdErrors[keyof PutApiRoomsIdErrors];

export type PutApiRoomsIdResponses = {
    /**
     * OK
     */
    200: Room;
};

export type PutApiRoomsIdResponse = PutApiRoomsIdResponses[keyof PutApiRoomsIdResponses];

export type GetApiUsersData = {
    body?: never;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: never;
    url: '/api/users/';
};

export type GetApiUsersErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type GetApiUsersError = GetApiUsersErrors[keyof GetApiUsersErrors];

export type GetApiUsersResponses = {
    /**
     * OK
     */
    200: PaginatedResponseModelsSanitizedUser;
};

export type GetApiUsersResponse = GetApiUsersResponses[keyof GetApiUsersResponses];

export type PostApiUsersData = {
    /**
     * Request body for users.userCreateDto
     */
    body: UserCreateDto;
    headers?: {
        Accept?: string;
    };
    path?: never;
    query?: never;
    url: '/api/users/';
};

export type PostApiUsersErrors = {
    /**
     * Bad Request _(validation or deserialization error)_
     */
    400: HttpError;
    /**
     * Internal Server Error _(panics)_
     */
    500: HttpError;
    default: unknown;
};

export type PostApiUsersError = PostApiUsersErrors[keyof PostApiUsersErrors];

export type PostApiUsersResponses = {
    /**
     * OK
     */
    200: UserCreateResponse;
};

export type PostApiUsersResponse = PostApiUsersResponses[keyof PostApiUsersResponses];
