// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * Account schema
 */
export const zAccount = z.object({
    accountCode: z.string().optional(),
    accountName: z.string().optional(),
    accountSubType: z.string().optional(),
    accountType: z.string().optional(),
    description: z.string().optional(),
    hotelId: z.int().gte(0).optional(),
    id: z.int().gte(0).optional(),
    isActive: z.boolean().optional(),
    isSystem: z.boolean().optional(),
    normalBalance: z.string().optional(),
    parentId: z.int().gte(0).optional()
});

/**
 * Country schema
 */
export const zCountry = z.object({
    id: z.int().gte(0).optional(),
    isIran: z.boolean().optional(),
    label: z.string().optional(),
    sanaId: z.string().optional(),
    sanaName: z.string().optional(),
    slug: z.string().optional()
});

/**
 * Expense schema
 */
export const zExpense = z.object({
    accountId: z.int().gte(0).optional(),
    amount: z.number().optional(),
    category: z.string().optional(),
    createdBy: z.int().gte(0).optional(),
    description: z.string().optional(),
    expenseDate: z.iso.datetime({ offset: true }).optional(),
    hotelId: z.int().gte(0).optional(),
    id: z.int().gte(0).optional(),
    notes: z.string().optional(),
    paymentMethod: z.string().optional(),
    paymentStatus: z.string().optional(),
    reference: z.string().optional(),
    vendor: z.string().optional()
});

/**
 * FamilyRelationship schema
 */
export const zFamilyRelationship = z.object({
    id: z.int().gte(0).optional(),
    label: z.string().optional(),
    sanaId: z.string().optional(),
    sanaName: z.string().optional(),
    slug: z.string().optional()
});

/**
 * Guest schema
 */
export const zGuest = z.object({
    address: z.string().optional(),
    companions: z.array(z.object({
        firstName: z.string().optional(),
        guestId: z.int().gte(0).optional(),
        id: z.int().gte(0).optional(),
        idNumber: z.string().optional(),
        lastName: z.string().optional(),
        nationalId: z.string().optional(),
        relation: z.string().optional()
    })).optional(),
    dateOfBirth: z.iso.datetime({ offset: true }).optional(),
    fatherName: z.string().optional(),
    firstName: z.string().min(2).max(50),
    gender: z.string().optional(),
    hotelId: z.int().gte(0).optional(),
    id: z.int().gte(0).optional(),
    idNumber: z.string().optional(),
    lastName: z.string().optional(),
    nationalId: z.string().optional(),
    nationality: z.string().optional(),
    occupation: z.string().optional(),
    phone: z.string().optional(),
    placeOfBirth: z.string().optional(),
    postalCode: z.string().optional(),
    reservations: z.array(z.object({
        breakfast: z.boolean().optional(),
        departureDate: z.iso.datetime({ offset: true }).optional(),
        destination: z.string().optional(),
        durationOfStay: z.int().optional(),
        entryDate: z.iso.datetime({ offset: true }).optional(),
        guestId: z.int().gte(0).optional(),
        guide: z.boolean().optional(),
        hotelId: z.string().optional(),
        id: z.int().gte(0).optional(),
        notes: z.string().optional(),
        numberOfPeople: z.int().optional(),
        origin: z.string().optional(),
        payment: z.object({
            agency: z.boolean().optional(),
            contractType: z.string().optional(),
            id: z.int().gte(0).optional(),
            isCash: z.boolean().optional(),
            referrer: z.string().optional(),
            reservationId: z.int().gte(0).optional()
        }).optional(),
        purposeOfTravel: z.string().optional(),
        reservationCode: z.string().optional(),
        roomPrice: z.number().optional(),
        rooms: z.array(z.object({
            amenities: z.array(z.object({
                id: z.int().gte(0).optional(),
                label: z.string().optional(),
                slug: z.string().optional()
            })).optional(),
            basePrice: z.number().optional(),
            capacity: z.int().optional(),
            description: z.string().optional(),
            floor: z.int().optional(),
            hotelId: z.int().gte(0).optional(),
            id: z.int().gte(0).optional(),
            name: z.string().optional(),
            roomNumber: z.string().min(1),
            roomType: z.object({
                colorHex: z.string().optional(),
                id: z.int().gte(0).optional(),
                label: z.string().optional(),
                slug: z.string().optional()
            }).optional(),
            roomTypeId: z.int().gte(0).optional(),
            status: z.object({
                colorHex: z.string().optional(),
                id: z.int().gte(0).optional(),
                label: z.string().optional(),
                slug: z.string().optional()
            }).optional(),
            statusId: z.int().gte(0).optional()
        })).optional(),
        userCheckIn: z.string().optional(),
        userCheckOut: z.string().optional()
    })).optional()
});

/**
 * GuestSettlementResponse schema
 */
export const zGuestSettlementResponse = z.object({
    balance: z.number().optional(),
    parkingTransactions: z.array(z.object({
        amountDue: z.number().optional(),
        amountPaid: z.number().optional(),
        entryTime: z.string().optional(),
        exitTime: z.string().optional(),
        hoursParked: z.number().optional(),
        id: z.int().gte(0).optional(),
        licensePlate: z.string().optional(),
        rateApplied: z.number().optional(),
        status: z.string().optional()
    })).optional(),
    reservations: z.array(z.object({
        checkInDate: z.string().optional(),
        checkOutDate: z.string().optional(),
        id: z.int().gte(0).optional(),
        paidAmount: z.number().optional(),
        reservationCode: z.string().optional(),
        roomPrice: z.number().optional(),
        status: z.string().optional()
    })).optional(),
    totalDue: z.number().optional(),
    totalPaid: z.number().optional(),
    totalParking: z.number().optional(),
    totalRoom: z.number().optional()
});

/**
 * GuestWithReservationRequest schema
 */
export const zGuestWithReservationRequest = z.object({
    companions: z.array(z.object({
        firstName: z.string().optional(),
        idNumber: z.string().optional(),
        lastName: z.string().optional(),
        nationalId: z.string().optional(),
        relation: z.string().optional()
    })).optional(),
    guest: z.object({
        address: z.string().optional(),
        companions: z.array(z.object({
            firstName: z.string().optional(),
            guestId: z.int().gte(0).optional(),
            id: z.int().gte(0).optional(),
            idNumber: z.string().optional(),
            lastName: z.string().optional(),
            nationalId: z.string().optional(),
            relation: z.string().optional()
        })).optional(),
        dateOfBirth: z.iso.datetime({ offset: true }).optional(),
        fatherName: z.string().optional(),
        firstName: z.string().min(2).max(50),
        gender: z.string().optional(),
        hotelId: z.int().gte(0).optional(),
        id: z.int().gte(0).optional(),
        idNumber: z.string().optional(),
        lastName: z.string().optional(),
        nationalId: z.string().optional(),
        nationality: z.string().optional(),
        occupation: z.string().optional(),
        phone: z.string().optional(),
        placeOfBirth: z.string().optional(),
        postalCode: z.string().optional(),
        reservations: z.array(z.object({
            breakfast: z.boolean().optional(),
            departureDate: z.iso.datetime({ offset: true }).optional(),
            destination: z.string().optional(),
            durationOfStay: z.int().optional(),
            entryDate: z.iso.datetime({ offset: true }).optional(),
            guestId: z.int().gte(0).optional(),
            guide: z.boolean().optional(),
            hotelId: z.string().optional(),
            id: z.int().gte(0).optional(),
            notes: z.string().optional(),
            numberOfPeople: z.int().optional(),
            origin: z.string().optional(),
            payment: z.object({
                agency: z.boolean().optional(),
                contractType: z.string().optional(),
                id: z.int().gte(0).optional(),
                isCash: z.boolean().optional(),
                referrer: z.string().optional(),
                reservationId: z.int().gte(0).optional()
            }).optional(),
            purposeOfTravel: z.string().optional(),
            reservationCode: z.string().optional(),
            roomPrice: z.number().optional(),
            rooms: z.array(z.object({
                amenities: z.array(z.object({
                    id: z.int().gte(0).optional(),
                    label: z.string().optional(),
                    slug: z.string().optional()
                })).optional(),
                basePrice: z.number().optional(),
                capacity: z.int().optional(),
                description: z.string().optional(),
                floor: z.int().optional(),
                hotelId: z.int().gte(0).optional(),
                id: z.int().gte(0).optional(),
                name: z.string().optional(),
                roomNumber: z.string().min(1),
                roomType: z.object({
                    colorHex: z.string().optional(),
                    id: z.int().gte(0).optional(),
                    label: z.string().optional(),
                    slug: z.string().optional()
                }).optional(),
                roomTypeId: z.int().gte(0).optional(),
                status: z.object({
                    colorHex: z.string().optional(),
                    id: z.int().gte(0).optional(),
                    label: z.string().optional(),
                    slug: z.string().optional()
                }).optional(),
                statusId: z.int().gte(0).optional()
            })).optional(),
            userCheckIn: z.string().optional(),
            userCheckOut: z.string().optional()
        })).optional()
    }).optional(),
    payment: z.object({
        agency: z.boolean().optional(),
        contractType: z.string().optional(),
        isCash: z.boolean().optional(),
        referrer: z.string().optional()
    }).optional(),
    reservation: z.object({
        breakfast: z.boolean().optional(),
        departureDate: z.iso.datetime({ offset: true }).optional(),
        destination: z.string().optional(),
        durationOfStay: z.int().optional(),
        entryDate: z.iso.datetime({ offset: true }).optional(),
        guide: z.boolean().optional(),
        notes: z.string().optional(),
        numberOfPeople: z.int().optional(),
        origin: z.string().optional(),
        purposeOfTravel: z.string().optional(),
        reservationCode: z.string().optional(),
        roomPrice: z.number().optional(),
        rooms: z.array(z.object({
            amenities: z.array(z.object({
                id: z.int().gte(0).optional(),
                label: z.string().optional(),
                slug: z.string().optional()
            })).optional(),
            basePrice: z.number().optional(),
            capacity: z.int().optional(),
            description: z.string().optional(),
            floor: z.int().optional(),
            hotelId: z.int().gte(0).optional(),
            id: z.int().gte(0).optional(),
            name: z.string().optional(),
            roomNumber: z.string().min(1),
            roomType: z.object({
                colorHex: z.string().optional(),
                id: z.int().gte(0).optional(),
                label: z.string().optional(),
                slug: z.string().optional()
            }).optional(),
            roomTypeId: z.int().gte(0).optional(),
            status: z.object({
                colorHex: z.string().optional(),
                id: z.int().gte(0).optional(),
                label: z.string().optional(),
                slug: z.string().optional()
            }).optional(),
            statusId: z.int().gte(0).optional()
        })).optional()
    }).optional()
});

/**
 * GuestWithReservationResponse schema
 */
export const zGuestWithReservationResponse = z.object({
    guest: z.object({
        address: z.string().optional(),
        companions: z.array(z.object({
            firstName: z.string().optional(),
            guestId: z.int().gte(0).optional(),
            id: z.int().gte(0).optional(),
            idNumber: z.string().optional(),
            lastName: z.string().optional(),
            nationalId: z.string().optional(),
            relation: z.string().optional()
        })).optional(),
        dateOfBirth: z.iso.datetime({ offset: true }).optional(),
        fatherName: z.string().optional(),
        firstName: z.string().min(2).max(50),
        gender: z.string().optional(),
        hotelId: z.int().gte(0).optional(),
        id: z.int().gte(0).optional(),
        idNumber: z.string().optional(),
        lastName: z.string().optional(),
        nationalId: z.string().optional(),
        nationality: z.string().optional(),
        occupation: z.string().optional(),
        phone: z.string().optional(),
        placeOfBirth: z.string().optional(),
        postalCode: z.string().optional(),
        reservations: z.array(z.object({
            breakfast: z.boolean().optional(),
            departureDate: z.iso.datetime({ offset: true }).optional(),
            destination: z.string().optional(),
            durationOfStay: z.int().optional(),
            entryDate: z.iso.datetime({ offset: true }).optional(),
            guestId: z.int().gte(0).optional(),
            guide: z.boolean().optional(),
            hotelId: z.string().optional(),
            id: z.int().gte(0).optional(),
            notes: z.string().optional(),
            numberOfPeople: z.int().optional(),
            origin: z.string().optional(),
            payment: z.object({
                agency: z.boolean().optional(),
                contractType: z.string().optional(),
                id: z.int().gte(0).optional(),
                isCash: z.boolean().optional(),
                referrer: z.string().optional(),
                reservationId: z.int().gte(0).optional()
            }).optional(),
            purposeOfTravel: z.string().optional(),
            reservationCode: z.string().optional(),
            roomPrice: z.number().optional(),
            rooms: z.array(z.object({
                amenities: z.array(z.object({
                    id: z.int().gte(0).optional(),
                    label: z.string().optional(),
                    slug: z.string().optional()
                })).optional(),
                basePrice: z.number().optional(),
                capacity: z.int().optional(),
                description: z.string().optional(),
                floor: z.int().optional(),
                hotelId: z.int().gte(0).optional(),
                id: z.int().gte(0).optional(),
                name: z.string().optional(),
                roomNumber: z.string().min(1),
                roomType: z.object({
                    colorHex: z.string().optional(),
                    id: z.int().gte(0).optional(),
                    label: z.string().optional(),
                    slug: z.string().optional()
                }).optional(),
                roomTypeId: z.int().gte(0).optional(),
                status: z.object({
                    colorHex: z.string().optional(),
                    id: z.int().gte(0).optional(),
                    label: z.string().optional(),
                    slug: z.string().optional()
                }).optional(),
                statusId: z.int().gte(0).optional()
            })).optional(),
            userCheckIn: z.string().optional(),
            userCheckOut: z.string().optional()
        })).optional()
    }).optional(),
    payment: z.object({
        agency: z.boolean().optional(),
        contractType: z.string().optional(),
        id: z.int().gte(0).optional(),
        isCash: z.boolean().optional(),
        referrer: z.string().optional(),
        reservationId: z.int().gte(0).optional()
    }).optional(),
    reservation: z.object({
        breakfast: z.boolean().optional(),
        departureDate: z.iso.datetime({ offset: true }).optional(),
        destination: z.string().optional(),
        durationOfStay: z.int().optional(),
        entryDate: z.iso.datetime({ offset: true }).optional(),
        guestId: z.int().gte(0).optional(),
        guide: z.boolean().optional(),
        hotelId: z.string().optional(),
        id: z.int().gte(0).optional(),
        notes: z.string().optional(),
        numberOfPeople: z.int().optional(),
        origin: z.string().optional(),
        payment: z.object({
            agency: z.boolean().optional(),
            contractType: z.string().optional(),
            id: z.int().gte(0).optional(),
            isCash: z.boolean().optional(),
            referrer: z.string().optional(),
            reservationId: z.int().gte(0).optional()
        }).optional(),
        purposeOfTravel: z.string().optional(),
        reservationCode: z.string().optional(),
        roomPrice: z.number().optional(),
        rooms: z.array(z.object({
            amenities: z.array(z.object({
                id: z.int().gte(0).optional(),
                label: z.string().optional(),
                slug: z.string().optional()
            })).optional(),
            basePrice: z.number().optional(),
            capacity: z.int().optional(),
            description: z.string().optional(),
            floor: z.int().optional(),
            hotelId: z.int().gte(0).optional(),
            id: z.int().gte(0).optional(),
            name: z.string().optional(),
            roomNumber: z.string().min(1),
            roomType: z.object({
                colorHex: z.string().optional(),
                id: z.int().gte(0).optional(),
                label: z.string().optional(),
                slug: z.string().optional()
            }).optional(),
            roomTypeId: z.int().gte(0).optional(),
            status: z.object({
                colorHex: z.string().optional(),
                id: z.int().gte(0).optional(),
                label: z.string().optional(),
                slug: z.string().optional()
            }).optional(),
            statusId: z.int().gte(0).optional()
        })).optional(),
        userCheckIn: z.string().optional(),
        userCheckOut: z.string().optional()
    }).optional()
});

/**
 * HTTPError schema
 */
export const zHttpError = z.object({
    detail: z.string().optional(),
    errors: z.array(z.object({
        more: z.record(z.string(), z.unknown()).optional(),
        name: z.string().optional(),
        reason: z.string().optional()
    })).optional(),
    instance: z.string().optional(),
    status: z.int().optional(),
    title: z.string().optional(),
    type: z.string().optional()
});

/**
 * Hotel schema
 */
export const zHotel = z.object({
    address: z.string().optional(),
    email: z.string().optional(),
    id: z.string().optional(),
    name: z.string().optional(),
    phone: z.string().optional()
});

/**
 * Income schema
 */
export const zIncome = z.object({
    accountId: z.int().gte(0).optional(),
    amount: z.number().optional(),
    category: z.string().optional(),
    createdBy: z.int().gte(0).optional(),
    description: z.string().optional(),
    hotelId: z.int().gte(0).optional(),
    id: z.int().gte(0).optional(),
    incomeDate: z.iso.datetime({ offset: true }).optional(),
    notes: z.string().optional(),
    paymentMethod: z.string().optional(),
    paymentStatus: z.string().optional(),
    reference: z.string().optional(),
    reservationId: z.int().gte(0).optional(),
    source: z.string().optional()
});

/**
 * InventoryItem schema
 */
export const zInventoryItem = z.object({
    category: z.string().optional(),
    description: z.string().optional(),
    hotelId: z.int().gte(0).optional(),
    id: z.int().gte(0).optional(),
    isActive: z.boolean().optional(),
    name: z.string().optional(),
    quantity: z.number().optional(),
    reorderLevel: z.number().optional(),
    unit: z.string().optional(),
    unitCost: z.number().optional()
});

/**
 * MeResponse schema
 */
export const zMeResponse = z.object({
    hotelId: z.string().optional(),
    permissions: z.array(z.string()).optional(),
    user: z.object({
        email: z.string().optional(),
        firstName: z.string().optional(),
        id: z.int().gte(0).optional(),
        lastName: z.string().optional(),
        userHotels: z.array(z.object({
            hotel: z.object({
                address: z.string().optional(),
                email: z.string().optional(),
                id: z.string().optional(),
                name: z.string().optional(),
                phone: z.string().optional()
            }).optional(),
            hotelId: z.string().optional()
        })).optional()
    }).optional()
});

/**
 * MealTransaction schema
 */
export const zMealTransaction = z.object({
    billId: z.int().gte(0).optional(),
    hotelId: z.int().gte(0).optional(),
    id: z.int().gte(0).optional(),
    inventoryItemId: z.int().gte(0).optional(),
    isExternal: z.boolean().optional(),
    itemName: z.string().optional(),
    notes: z.string().optional(),
    quantity: z.number().optional(),
    totalPrice: z.number().optional(),
    unitPrice: z.number().optional()
});

/**
 * Nationality schema
 */
export const zNationality = z.object({
    id: z.int().gte(0).optional(),
    label: z.string().optional(),
    sanaId: z.string().optional(),
    sanaName: z.string().optional(),
    slug: z.string().optional()
});

/**
 * Occupation schema
 */
export const zOccupation = z.object({
    id: z.int().gte(0).optional(),
    label: z.string().optional(),
    sanaId: z.string().optional(),
    sanaName: z.string().optional(),
    slug: z.string().optional()
});

/**
 * PaginatedResponse_models.Account schema
 */
export const zPaginatedResponseModelsAccount = z.object({
    data: z.array(z.object({
        accountCode: z.string().optional(),
        accountName: z.string().optional(),
        accountSubType: z.string().optional(),
        accountType: z.string().optional(),
        description: z.string().optional(),
        hotelId: z.int().gte(0).optional(),
        id: z.int().gte(0).optional(),
        isActive: z.boolean().optional(),
        isSystem: z.boolean().optional(),
        normalBalance: z.string().optional(),
        parentId: z.int().gte(0).optional()
    })).optional(),
    limit: z.int().optional(),
    page: z.int().optional(),
    total: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    totalPages: z.int().optional()
});

/**
 * PaginatedResponse_models.Amenity schema
 */
export const zPaginatedResponseModelsAmenity = z.object({
    data: z.array(z.object({
        id: z.int().gte(0).optional(),
        label: z.string().optional(),
        slug: z.string().optional()
    })).optional(),
    limit: z.int().optional(),
    page: z.int().optional(),
    total: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    totalPages: z.int().optional()
});

/**
 * PaginatedResponse_models.Expense schema
 */
export const zPaginatedResponseModelsExpense = z.object({
    data: z.array(z.object({
        accountId: z.int().gte(0).optional(),
        amount: z.number().optional(),
        category: z.string().optional(),
        createdBy: z.int().gte(0).optional(),
        description: z.string().optional(),
        expenseDate: z.iso.datetime({ offset: true }).optional(),
        hotelId: z.int().gte(0).optional(),
        id: z.int().gte(0).optional(),
        notes: z.string().optional(),
        paymentMethod: z.string().optional(),
        paymentStatus: z.string().optional(),
        reference: z.string().optional(),
        vendor: z.string().optional()
    })).optional(),
    limit: z.int().optional(),
    page: z.int().optional(),
    total: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    totalPages: z.int().optional()
});

/**
 * PaginatedResponse_models.Guest schema
 */
export const zPaginatedResponseModelsGuest = z.object({
    data: z.array(z.object({
        address: z.string().optional(),
        companions: z.array(z.object({
            firstName: z.string().optional(),
            guestId: z.int().gte(0).optional(),
            id: z.int().gte(0).optional(),
            idNumber: z.string().optional(),
            lastName: z.string().optional(),
            nationalId: z.string().optional(),
            relation: z.string().optional()
        })).optional(),
        dateOfBirth: z.iso.datetime({ offset: true }).optional(),
        fatherName: z.string().optional(),
        firstName: z.string().min(2).max(50),
        gender: z.string().optional(),
        hotelId: z.int().gte(0).optional(),
        id: z.int().gte(0).optional(),
        idNumber: z.string().optional(),
        lastName: z.string().optional(),
        nationalId: z.string().optional(),
        nationality: z.string().optional(),
        occupation: z.string().optional(),
        phone: z.string().optional(),
        placeOfBirth: z.string().optional(),
        postalCode: z.string().optional(),
        reservations: z.array(z.object({
            breakfast: z.boolean().optional(),
            departureDate: z.iso.datetime({ offset: true }).optional(),
            destination: z.string().optional(),
            durationOfStay: z.int().optional(),
            entryDate: z.iso.datetime({ offset: true }).optional(),
            guestId: z.int().gte(0).optional(),
            guide: z.boolean().optional(),
            hotelId: z.string().optional(),
            id: z.int().gte(0).optional(),
            notes: z.string().optional(),
            numberOfPeople: z.int().optional(),
            origin: z.string().optional(),
            payment: z.object({
                agency: z.boolean().optional(),
                contractType: z.string().optional(),
                id: z.int().gte(0).optional(),
                isCash: z.boolean().optional(),
                referrer: z.string().optional(),
                reservationId: z.int().gte(0).optional()
            }).optional(),
            purposeOfTravel: z.string().optional(),
            reservationCode: z.string().optional(),
            roomPrice: z.number().optional(),
            rooms: z.array(z.object({
                amenities: z.array(z.object({
                    id: z.int().gte(0).optional(),
                    label: z.string().optional(),
                    slug: z.string().optional()
                })).optional(),
                basePrice: z.number().optional(),
                capacity: z.int().optional(),
                description: z.string().optional(),
                floor: z.int().optional(),
                hotelId: z.int().gte(0).optional(),
                id: z.int().gte(0).optional(),
                name: z.string().optional(),
                roomNumber: z.string().min(1),
                roomType: z.object({
                    colorHex: z.string().optional(),
                    id: z.int().gte(0).optional(),
                    label: z.string().optional(),
                    slug: z.string().optional()
                }).optional(),
                roomTypeId: z.int().gte(0).optional(),
                status: z.object({
                    colorHex: z.string().optional(),
                    id: z.int().gte(0).optional(),
                    label: z.string().optional(),
                    slug: z.string().optional()
                }).optional(),
                statusId: z.int().gte(0).optional()
            })).optional(),
            userCheckIn: z.string().optional(),
            userCheckOut: z.string().optional()
        })).optional()
    })).optional(),
    limit: z.int().optional(),
    page: z.int().optional(),
    total: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    totalPages: z.int().optional()
});

/**
 * PaginatedResponse_models.Hotel schema
 */
export const zPaginatedResponseModelsHotel = z.object({
    data: z.array(z.object({
        address: z.string().optional(),
        email: z.string().optional(),
        id: z.string().optional(),
        name: z.string().optional(),
        phone: z.string().optional()
    })).optional(),
    limit: z.int().optional(),
    page: z.int().optional(),
    total: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    totalPages: z.int().optional()
});

/**
 * PaginatedResponse_models.Income schema
 */
export const zPaginatedResponseModelsIncome = z.object({
    data: z.array(z.object({
        accountId: z.int().gte(0).optional(),
        amount: z.number().optional(),
        category: z.string().optional(),
        createdBy: z.int().gte(0).optional(),
        description: z.string().optional(),
        hotelId: z.int().gte(0).optional(),
        id: z.int().gte(0).optional(),
        incomeDate: z.iso.datetime({ offset: true }).optional(),
        notes: z.string().optional(),
        paymentMethod: z.string().optional(),
        paymentStatus: z.string().optional(),
        reference: z.string().optional(),
        reservationId: z.int().gte(0).optional(),
        source: z.string().optional()
    })).optional(),
    limit: z.int().optional(),
    page: z.int().optional(),
    total: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    totalPages: z.int().optional()
});

/**
 * PaginatedResponse_models.InventoryItem schema
 */
export const zPaginatedResponseModelsInventoryItem = z.object({
    data: z.array(z.object({
        category: z.string().optional(),
        description: z.string().optional(),
        hotelId: z.int().gte(0).optional(),
        id: z.int().gte(0).optional(),
        isActive: z.boolean().optional(),
        name: z.string().optional(),
        quantity: z.number().optional(),
        reorderLevel: z.number().optional(),
        unit: z.string().optional(),
        unitCost: z.number().optional()
    })).optional(),
    limit: z.int().optional(),
    page: z.int().optional(),
    total: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    totalPages: z.int().optional()
});

/**
 * PaginatedResponse_models.MealTransaction schema
 */
export const zPaginatedResponseModelsMealTransaction = z.object({
    data: z.array(z.object({
        billId: z.int().gte(0).optional(),
        hotelId: z.int().gte(0).optional(),
        id: z.int().gte(0).optional(),
        inventoryItemId: z.int().gte(0).optional(),
        isExternal: z.boolean().optional(),
        itemName: z.string().optional(),
        notes: z.string().optional(),
        quantity: z.number().optional(),
        totalPrice: z.number().optional(),
        unitPrice: z.number().optional()
    })).optional(),
    limit: z.int().optional(),
    page: z.int().optional(),
    total: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    totalPages: z.int().optional()
});

/**
 * PaginatedResponse_models.ParkingLot schema
 */
export const zPaginatedResponseModelsParkingLot = z.object({
    data: z.array(z.object({
        dailyRate: z.number().optional(),
        description: z.string().optional(),
        hotelId: z.int().gte(0).optional(),
        hourlyRate: z.number().optional(),
        id: z.int().gte(0).optional(),
        location: z.string().optional(),
        name: z.string().optional(),
        status: z.string().optional(),
        totalSpots: z.int().optional()
    })).optional(),
    limit: z.int().optional(),
    page: z.int().optional(),
    total: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    totalPages: z.int().optional()
});

/**
 * PaginatedResponse_models.ParkingSpot schema
 */
export const zPaginatedResponseModelsParkingSpot = z.object({
    data: z.array(z.object({
        description: z.string().optional(),
        floor: z.string().optional(),
        id: z.int().gte(0).optional(),
        isCovered: z.boolean().optional(),
        lotId: z.int().gte(0).optional(),
        spotNumber: z.string().optional(),
        spotType: z.string().optional(),
        status: z.string().optional()
    })).optional(),
    limit: z.int().optional(),
    page: z.int().optional(),
    total: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    totalPages: z.int().optional()
});

/**
 * PaginatedResponse_models.ParkingSpotStatus schema
 */
export const zPaginatedResponseModelsParkingSpotStatus = z.object({
    data: z.array(z.object({
        id: z.int().gte(0).optional(),
        label: z.string().optional(),
        slug: z.string().optional()
    })).optional(),
    limit: z.int().optional(),
    page: z.int().optional(),
    total: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    totalPages: z.int().optional()
});

/**
 * PaginatedResponse_models.ParkingSpotType schema
 */
export const zPaginatedResponseModelsParkingSpotType = z.object({
    data: z.array(z.object({
        id: z.int().gte(0).optional(),
        label: z.string().optional(),
        slug: z.string().optional()
    })).optional(),
    limit: z.int().optional(),
    page: z.int().optional(),
    total: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    totalPages: z.int().optional()
});

/**
 * PaginatedResponse_models.ParkingTransaction schema
 */
export const zPaginatedResponseModelsParkingTransaction = z.object({
    data: z.array(z.object({
        amountDue: z.number().optional(),
        amountPaid: z.number().optional(),
        entryTime: z.iso.datetime({ offset: true }).optional(),
        exitTime: z.iso.datetime({ offset: true }).optional(),
        guestId: z.int().gte(0).optional(),
        hoursParked: z.number().optional(),
        id: z.int().gte(0).optional(),
        licensePlate: z.string().optional(),
        lotId: z.int().gte(0).optional(),
        notes: z.string().optional(),
        paymentMethod: z.string().optional(),
        paymentStatus: z.string().optional(),
        rateApplied: z.number().optional(),
        reservationId: z.int().gte(0).optional(),
        spotId: z.int().gte(0).optional(),
        status: z.string().optional()
    })).optional(),
    limit: z.int().optional(),
    page: z.int().optional(),
    total: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    totalPages: z.int().optional()
});

/**
 * PaginatedResponse_models.PermissionTemplate schema
 */
export const zPaginatedResponseModelsPermissionTemplate = z.object({
    data: z.array(z.object({
        description: z.string().optional(),
        id: z.int().gte(0).optional(),
        label: z.string().optional(),
        permissions: z.array(z.object({
            action: z.string().optional(),
            category: z.object({
                id: z.int().gte(0).optional(),
                label: z.string().optional(),
                slug: z.string().optional()
            }).optional(),
            categoryId: z.int().gte(0).optional(),
            id: z.int().gte(0).optional(),
            resource: z.string().optional()
        })).optional(),
        slug: z.string().optional()
    })).optional(),
    limit: z.int().optional(),
    page: z.int().optional(),
    total: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    totalPages: z.int().optional()
});

/**
 * PaginatedResponse_models.Reservation schema
 */
export const zPaginatedResponseModelsReservation = z.object({
    data: z.array(z.object({
        breakfast: z.boolean().optional(),
        departureDate: z.iso.datetime({ offset: true }).optional(),
        destination: z.string().optional(),
        durationOfStay: z.int().optional(),
        entryDate: z.iso.datetime({ offset: true }).optional(),
        guestId: z.int().gte(0).optional(),
        guide: z.boolean().optional(),
        hotelId: z.string().optional(),
        id: z.int().gte(0).optional(),
        notes: z.string().optional(),
        numberOfPeople: z.int().optional(),
        origin: z.string().optional(),
        payment: z.object({
            agency: z.boolean().optional(),
            contractType: z.string().optional(),
            id: z.int().gte(0).optional(),
            isCash: z.boolean().optional(),
            referrer: z.string().optional(),
            reservationId: z.int().gte(0).optional()
        }).optional(),
        purposeOfTravel: z.string().optional(),
        reservationCode: z.string().optional(),
        roomPrice: z.number().optional(),
        rooms: z.array(z.object({
            amenities: z.array(z.object({
                id: z.int().gte(0).optional(),
                label: z.string().optional(),
                slug: z.string().optional()
            })).optional(),
            basePrice: z.number().optional(),
            capacity: z.int().optional(),
            description: z.string().optional(),
            floor: z.int().optional(),
            hotelId: z.int().gte(0).optional(),
            id: z.int().gte(0).optional(),
            name: z.string().optional(),
            roomNumber: z.string().min(1),
            roomType: z.object({
                colorHex: z.string().optional(),
                id: z.int().gte(0).optional(),
                label: z.string().optional(),
                slug: z.string().optional()
            }).optional(),
            roomTypeId: z.int().gte(0).optional(),
            status: z.object({
                colorHex: z.string().optional(),
                id: z.int().gte(0).optional(),
                label: z.string().optional(),
                slug: z.string().optional()
            }).optional(),
            statusId: z.int().gte(0).optional()
        })).optional(),
        userCheckIn: z.string().optional(),
        userCheckOut: z.string().optional()
    })).optional(),
    limit: z.int().optional(),
    page: z.int().optional(),
    total: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    totalPages: z.int().optional()
});

/**
 * PaginatedResponse_models.RestaurantBill schema
 */
export const zPaginatedResponseModelsRestaurantBill = z.object({
    data: z.array(z.object({
        billDate: z.iso.datetime({ offset: true }).optional(),
        discountAmount: z.number().optional(),
        externalRestaurant: z.string().optional(),
        guestId: z.int().gte(0).optional(),
        hotelId: z.int().gte(0).optional(),
        id: z.int().gte(0).optional(),
        isExternal: z.boolean().optional(),
        notes: z.string().optional(),
        reservationId: z.int().gte(0).optional(),
        roomId: z.int().gte(0).optional(),
        settled: z.boolean().optional(),
        settledAt: z.iso.datetime({ offset: true }).optional(),
        settledBy: z.int().gte(0).optional(),
        status: z.string().optional(),
        subtotal: z.number().optional(),
        taxAmount: z.number().optional(),
        totalAmount: z.number().optional()
    })).optional(),
    limit: z.int().optional(),
    page: z.int().optional(),
    total: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    totalPages: z.int().optional()
});

/**
 * PaginatedResponse_models.Room schema
 */
export const zPaginatedResponseModelsRoom = z.object({
    data: z.array(z.object({
        amenities: z.array(z.object({
            id: z.int().gte(0).optional(),
            label: z.string().optional(),
            slug: z.string().optional()
        })).optional(),
        basePrice: z.number().optional(),
        capacity: z.int().optional(),
        description: z.string().optional(),
        floor: z.int().optional(),
        hotelId: z.int().gte(0).optional(),
        id: z.int().gte(0).optional(),
        name: z.string().optional(),
        roomNumber: z.string().min(1),
        roomType: z.object({
            colorHex: z.string().optional(),
            id: z.int().gte(0).optional(),
            label: z.string().optional(),
            slug: z.string().optional()
        }).optional(),
        roomTypeId: z.int().gte(0).optional(),
        status: z.object({
            colorHex: z.string().optional(),
            id: z.int().gte(0).optional(),
            label: z.string().optional(),
            slug: z.string().optional()
        }).optional(),
        statusId: z.int().gte(0).optional()
    })).optional(),
    limit: z.int().optional(),
    page: z.int().optional(),
    total: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    totalPages: z.int().optional()
});

/**
 * PaginatedResponse_models.RoomStatus schema
 */
export const zPaginatedResponseModelsRoomStatus = z.object({
    data: z.array(z.object({
        colorHex: z.string().optional(),
        id: z.int().gte(0).optional(),
        label: z.string().optional(),
        slug: z.string().optional()
    })).optional(),
    limit: z.int().optional(),
    page: z.int().optional(),
    total: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    totalPages: z.int().optional()
});

/**
 * PaginatedResponse_models.RoomType schema
 */
export const zPaginatedResponseModelsRoomType = z.object({
    data: z.array(z.object({
        colorHex: z.string().optional(),
        id: z.int().gte(0).optional(),
        label: z.string().optional(),
        slug: z.string().optional()
    })).optional(),
    limit: z.int().optional(),
    page: z.int().optional(),
    total: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    totalPages: z.int().optional()
});

/**
 * PaginatedResponse_models.SanitizedUser schema
 */
export const zPaginatedResponseModelsSanitizedUser = z.object({
    data: z.array(z.object({
        email: z.string().optional(),
        firstName: z.string().optional(),
        id: z.int().gte(0).optional(),
        lastName: z.string().optional(),
        userHotels: z.array(z.object({
            hotel: z.object({
                address: z.string().optional(),
                email: z.string().optional(),
                id: z.string().optional(),
                name: z.string().optional(),
                phone: z.string().optional()
            }).optional(),
            hotelId: z.string().optional()
        })).optional()
    })).optional(),
    limit: z.int().optional(),
    page: z.int().optional(),
    total: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    totalPages: z.int().optional()
});

/**
 * PaginatedResponse_models.Vehicle schema
 */
export const zPaginatedResponseModelsVehicle = z.object({
    data: z.array(z.object({
        color: z.string().optional(),
        guestId: z.int().gte(0).optional(),
        id: z.int().gte(0).optional(),
        isRegistered: z.boolean().optional(),
        licensePlate: z.string().optional(),
        make: z.string().optional(),
        model: z.string().optional(),
        notes: z.string().optional(),
        vehicleType: z.string().optional()
    })).optional(),
    limit: z.int().optional(),
    page: z.int().optional(),
    total: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    totalPages: z.int().optional()
});

/**
 * ParkingLot schema
 */
export const zParkingLot = z.object({
    dailyRate: z.number().optional(),
    description: z.string().optional(),
    hotelId: z.int().gte(0).optional(),
    hourlyRate: z.number().optional(),
    id: z.int().gte(0).optional(),
    location: z.string().optional(),
    name: z.string().optional(),
    status: z.string().optional(),
    totalSpots: z.int().optional()
});

/**
 * ParkingSpot schema
 */
export const zParkingSpot = z.object({
    description: z.string().optional(),
    floor: z.string().optional(),
    id: z.int().gte(0).optional(),
    isCovered: z.boolean().optional(),
    lotId: z.int().gte(0).optional(),
    spotNumber: z.string().optional(),
    spotType: z.string().optional(),
    status: z.string().optional()
});

/**
 * ParkingStats schema
 */
export const zParkingStats = z.object({
    availableSpots: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    lots: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    spots: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional()
});

/**
 * ParkingTransaction schema
 */
export const zParkingTransaction = z.object({
    amountDue: z.number().optional(),
    amountPaid: z.number().optional(),
    entryTime: z.iso.datetime({ offset: true }).optional(),
    exitTime: z.iso.datetime({ offset: true }).optional(),
    guestId: z.int().gte(0).optional(),
    hoursParked: z.number().optional(),
    id: z.int().gte(0).optional(),
    licensePlate: z.string().optional(),
    lotId: z.int().gte(0).optional(),
    notes: z.string().optional(),
    paymentMethod: z.string().optional(),
    paymentStatus: z.string().optional(),
    rateApplied: z.number().optional(),
    reservationId: z.int().gte(0).optional(),
    spotId: z.int().gte(0).optional(),
    status: z.string().optional()
});

/**
 * Reservation schema
 */
export const zReservation = z.object({
    breakfast: z.boolean().optional(),
    departureDate: z.iso.datetime({ offset: true }).optional(),
    destination: z.string().optional(),
    durationOfStay: z.int().optional(),
    entryDate: z.iso.datetime({ offset: true }).optional(),
    guestId: z.int().gte(0).optional(),
    guide: z.boolean().optional(),
    hotelId: z.string().optional(),
    id: z.int().gte(0).optional(),
    notes: z.string().optional(),
    numberOfPeople: z.int().optional(),
    origin: z.string().optional(),
    payment: z.object({
        agency: z.boolean().optional(),
        contractType: z.string().optional(),
        id: z.int().gte(0).optional(),
        isCash: z.boolean().optional(),
        referrer: z.string().optional(),
        reservationId: z.int().gte(0).optional()
    }).optional(),
    purposeOfTravel: z.string().optional(),
    reservationCode: z.string().optional(),
    roomPrice: z.number().optional(),
    rooms: z.array(z.object({
        amenities: z.array(z.object({
            id: z.int().gte(0).optional(),
            label: z.string().optional(),
            slug: z.string().optional()
        })).optional(),
        basePrice: z.number().optional(),
        capacity: z.int().optional(),
        description: z.string().optional(),
        floor: z.int().optional(),
        hotelId: z.int().gte(0).optional(),
        id: z.int().gte(0).optional(),
        name: z.string().optional(),
        roomNumber: z.string().min(1),
        roomType: z.object({
            colorHex: z.string().optional(),
            id: z.int().gte(0).optional(),
            label: z.string().optional(),
            slug: z.string().optional()
        }).optional(),
        roomTypeId: z.int().gte(0).optional(),
        status: z.object({
            colorHex: z.string().optional(),
            id: z.int().gte(0).optional(),
            label: z.string().optional(),
            slug: z.string().optional()
        }).optional(),
        statusId: z.int().gte(0).optional()
    })).optional(),
    userCheckIn: z.string().optional(),
    userCheckOut: z.string().optional()
});

/**
 * RestaurantBill schema
 */
export const zRestaurantBill = z.object({
    billDate: z.iso.datetime({ offset: true }).optional(),
    discountAmount: z.number().optional(),
    externalRestaurant: z.string().optional(),
    guestId: z.int().gte(0).optional(),
    hotelId: z.int().gte(0).optional(),
    id: z.int().gte(0).optional(),
    isExternal: z.boolean().optional(),
    notes: z.string().optional(),
    reservationId: z.int().gte(0).optional(),
    roomId: z.int().gte(0).optional(),
    settled: z.boolean().optional(),
    settledAt: z.iso.datetime({ offset: true }).optional(),
    settledBy: z.int().gte(0).optional(),
    status: z.string().optional(),
    subtotal: z.number().optional(),
    taxAmount: z.number().optional(),
    totalAmount: z.number().optional()
});

/**
 * RestaurantStats schema
 */
export const zRestaurantStats = z.object({
    externalRevenue: z.number().optional(),
    internalRevenue: z.number().optional(),
    totalBills: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    totalMeals: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    totalRevenue: z.number().optional()
});

/**
 * Room schema
 */
export const zRoom = z.object({
    amenities: z.array(z.object({
        id: z.int().gte(0).optional(),
        label: z.string().optional(),
        slug: z.string().optional()
    })).optional(),
    basePrice: z.number().optional(),
    capacity: z.int().optional(),
    description: z.string().optional(),
    floor: z.int().optional(),
    hotelId: z.int().gte(0).optional(),
    id: z.int().gte(0).optional(),
    name: z.string().optional(),
    roomNumber: z.string().min(1),
    roomType: z.object({
        colorHex: z.string().optional(),
        id: z.int().gte(0).optional(),
        label: z.string().optional(),
        slug: z.string().optional()
    }).optional(),
    roomTypeId: z.int().gte(0).optional(),
    status: z.object({
        colorHex: z.string().optional(),
        id: z.int().gte(0).optional(),
        label: z.string().optional(),
        slug: z.string().optional()
    }).optional(),
    statusId: z.int().gte(0).optional()
});

/**
 * SanaGuestResponse schema
 */
export const zSanaGuestResponse = z.object({
    guest: z.object({
        firstName: z.string().optional(),
        lastName: z.string().optional(),
        nationalId: z.string().optional()
    }).optional(),
    guestId: z.int().gte(0).optional(),
    id: z.int().gte(0).optional(),
    recordMosafer: z.int().optional(),
    shomareOtagh: z.string().optional(),
    shomarePaziresh: z.string().optional(),
    syncTime: z.string().optional()
});

/**
 * SanaRoomResponse schema
 */
export const zSanaRoomResponse = z.object({
    hotelId: z.string().optional(),
    id: z.int().gte(0).optional(),
    isSynced: z.boolean().optional(),
    lastError: z.string().optional(),
    lastSyncTime: z.string().optional(),
    rac: z.string().optional(),
    room: z.object({
        id: z.int().gte(0).optional(),
        roomNumber: z.string().optional()
    }).optional()
});

/**
 * SanitizedUser schema
 */
export const zSanitizedUser = z.object({
    email: z.string().optional(),
    firstName: z.string().optional(),
    id: z.int().gte(0).optional(),
    lastName: z.string().optional(),
    userHotels: z.array(z.object({
        hotel: z.object({
            address: z.string().optional(),
            email: z.string().optional(),
            id: z.string().optional(),
            name: z.string().optional(),
            phone: z.string().optional()
        }).optional(),
        hotelId: z.string().optional()
    })).optional()
});

/**
 * SettleGuestRequest schema
 */
export const zSettleGuestRequest = z.object({
    amount: z.number().optional(),
    notes: z.string().optional(),
    parkingTxnIds: z.array(z.int().gte(0)).optional(),
    paymentMethod: z.string().optional(),
    reference: z.string().optional(),
    reservationIds: z.array(z.int().gte(0)).optional()
});

/**
 * TravelReason schema
 */
export const zTravelReason = z.object({
    id: z.int().gte(0).optional(),
    label: z.string().optional(),
    sanaId: z.string().optional(),
    sanaName: z.string().optional(),
    slug: z.string().optional()
});

/**
 * Vehicle schema
 */
export const zVehicle = z.object({
    color: z.string().optional(),
    guestId: z.int().gte(0).optional(),
    id: z.int().gte(0).optional(),
    isRegistered: z.boolean().optional(),
    licensePlate: z.string().optional(),
    make: z.string().optional(),
    model: z.string().optional(),
    notes: z.string().optional(),
    vehicleType: z.string().optional()
});

/**
 * bool schema
 */
export const zBool = z.boolean();

/**
 * loginDto schema
 */
export const zLoginDto = z.object({
    email: z.string().optional(),
    password: z.string().optional()
});

/**
 * loginResponse schema
 */
export const zLoginResponse = z.object({
    hotelId: z.string().optional(),
    permissions: z.array(z.string()).optional(),
    user: z.object({
        email: z.string().optional(),
        firstName: z.string().optional(),
        id: z.int().gte(0).optional(),
        lastName: z.string().optional(),
        userHotels: z.array(z.object({
            hotel: z.object({
                address: z.string().optional(),
                email: z.string().optional(),
                id: z.string().optional(),
                name: z.string().optional(),
                phone: z.string().optional()
            }).optional(),
            hotelId: z.string().optional()
        })).optional()
    }).optional()
});

/**
 * okResponse schema
 */
export const zOkResponse = z.object({
    ok: z.boolean().optional()
});

/**
 * permissionsResponse schema
 */
export const zPermissionsResponse = z.object({
    data: z.array(z.object({
        action: z.string().optional(),
        category: z.object({
            id: z.int().gte(0).optional(),
            label: z.string().optional(),
            slug: z.string().optional()
        }).optional(),
        categoryId: z.int().gte(0).optional(),
        id: z.int().gte(0).optional(),
        resource: z.string().optional()
    })).optional()
});

/**
 * string schema
 */
export const zString = z.string();

/**
 * unknown-interface schema
 */
export const zUnknownInterface = z.unknown();

/**
 * userCreateDto schema
 */
export const zUserCreateDto = z.object({
    email: z.string().optional(),
    firstName: z.string().optional(),
    lastName: z.string().optional(),
    password: z.string().optional()
});

/**
 * userCreateResponse schema
 */
export const zUserCreateResponse = z.object({
    id: z.int().gte(0).optional()
});

/**
 * userPermissionsResponse schema
 */
export const zUserPermissionsResponse = z.object({
    permissions: z.array(z.object({
        action: z.string().optional(),
        category: z.object({
            id: z.int().gte(0).optional(),
            label: z.string().optional(),
            slug: z.string().optional()
        }).optional(),
        granted: z.boolean().optional(),
        label: z.string().optional(),
        page: z.string().optional(),
        permissionId: z.int().gte(0).optional()
    })).optional(),
    userId: z.int().gte(0).optional()
});

/**
 * userUpdateDto schema
 */
export const zUserUpdateDto = z.object({
    email: z.string().optional(),
    firstName: z.string().optional(),
    lastName: z.string().optional()
});

export const zGetApiAccountingAccountsHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiAccountingAccountsQuery = z.object({
    limit: z.int().optional(),
    page: z.int().optional()
});

/**
 * OK
 */
export const zGetApiAccountingAccountsResponse = zPaginatedResponseModelsAccount;

/**
 * Request body for models.Account
 */
export const zPostApiAccountingAccountsBody = zAccount;

export const zPostApiAccountingAccountsHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zPostApiAccountingAccountsResponse = zAccount;

export const zGetApiAccountingExpensesHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiAccountingExpensesQuery = z.object({
    limit: z.int().optional(),
    page: z.int().optional()
});

/**
 * OK
 */
export const zGetApiAccountingExpensesResponse = zPaginatedResponseModelsExpense;

/**
 * Request body for models.Expense
 */
export const zPostApiAccountingExpensesBody = zExpense;

export const zPostApiAccountingExpensesHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zPostApiAccountingExpensesResponse = zExpense;

export const zGetApiAccountingIncomeHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiAccountingIncomeQuery = z.object({
    limit: z.int().optional(),
    page: z.int().optional()
});

/**
 * OK
 */
export const zGetApiAccountingIncomeResponse = zPaginatedResponseModelsIncome;

/**
 * Request body for models.Income
 */
export const zPostApiAccountingIncomeBody = zIncome;

export const zPostApiAccountingIncomeHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zPostApiAccountingIncomeResponse = zIncome;

/**
 * Request body for auth.loginDto
 */
export const zPostApiAuthLoginBody = zLoginDto;

export const zPostApiAuthLoginHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zPostApiAuthLoginResponse = zLoginResponse;

export const zPostApiAuthLogoutHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zPostApiAuthLogoutResponse = zBool;

export const zGetApiAuthMeHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zGetApiAuthMeResponse = zMeResponse;

export const zGetApiGuestsHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiGuestsQuery = z.object({
    limit: z.int().optional(),
    page: z.int().optional()
});

/**
 * OK
 */
export const zGetApiGuestsResponse = zPaginatedResponseModelsGuest;

/**
 * Request body for models.Guest
 */
export const zPostApiGuestsBody = zGuest;

export const zPostApiGuestsHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zPostApiGuestsResponse = zGuest;

/**
 * Request body for guests.GuestWithReservationRequest
 */
export const zPostApiGuestsWithReservationBody = zGuestWithReservationRequest;

export const zPostApiGuestsWithReservationHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zPostApiGuestsWithReservationResponse = zGuestWithReservationResponse;

export const zGetApiGuestsIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiGuestsIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zGetApiGuestsIdResponse = zGuest;

/**
 * Request body for models.Guest
 */
export const zPutApiGuestsIdBody = zGuest;

export const zPutApiGuestsIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zPutApiGuestsIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zPutApiGuestsIdResponse = zGuest;

export const zGetApiGuestsIdSettleHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiGuestsIdSettlePath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zGetApiGuestsIdSettleResponse = zGuestSettlementResponse;

/**
 * Request body for guests.SettleGuestRequest
 */
export const zPostApiGuestsIdSettleBody = zSettleGuestRequest;

export const zPostApiGuestsIdSettleHeaders = z.object({
    Accept: z.string().optional()
});

export const zPostApiGuestsIdSettlePath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zPostApiGuestsIdSettleResponse = zOkResponse;

export const zGetApiHealthzHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zGetApiHealthzResponse = zString;

export const zGetApiHotelsHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiHotelsQuery = z.object({
    limit: z.int().optional(),
    page: z.int().optional()
});

/**
 * OK
 */
export const zGetApiHotelsResponse = zPaginatedResponseModelsHotel;

/**
 * Request body for models.Hotel
 */
export const zPostApiHotelsBody = zHotel;

export const zPostApiHotelsHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zPostApiHotelsResponse = zHotel;

export const zDeleteApiHotelsIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zDeleteApiHotelsIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zDeleteApiHotelsIdResponse = zOkResponse;

export const zGetApiHotelsIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiHotelsIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zGetApiHotelsIdResponse = zHotel;

/**
 * Request body for models.Hotel
 */
export const zPutApiHotelsIdBody = zHotel;

export const zPutApiHotelsIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zPutApiHotelsIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zPutApiHotelsIdResponse = zHotel;

export const zGetApiParkingLotsHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiParkingLotsQuery = z.object({
    limit: z.int().optional(),
    page: z.int().optional()
});

/**
 * OK
 */
export const zGetApiParkingLotsResponse = zPaginatedResponseModelsParkingLot;

/**
 * Request body for models.ParkingLot
 */
export const zPostApiParkingLotsBody = zParkingLot;

export const zPostApiParkingLotsHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zPostApiParkingLotsResponse = zParkingLot;

export const zDeleteApiParkingLotsIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zDeleteApiParkingLotsIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zDeleteApiParkingLotsIdResponse = zOkResponse;

export const zGetApiParkingLotsIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiParkingLotsIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zGetApiParkingLotsIdResponse = zParkingLot;

/**
 * Request body for models.ParkingLot
 */
export const zPutApiParkingLotsIdBody = zParkingLot;

export const zPutApiParkingLotsIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zPutApiParkingLotsIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zPutApiParkingLotsIdResponse = zParkingLot;

export const zGetApiParkingSpotsHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiParkingSpotsQuery = z.object({
    limit: z.int().optional(),
    page: z.int().optional()
});

/**
 * OK
 */
export const zGetApiParkingSpotsResponse = zPaginatedResponseModelsParkingSpot;

/**
 * Request body for models.ParkingSpot
 */
export const zPostApiParkingSpotsBody = zParkingSpot;

export const zPostApiParkingSpotsHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zPostApiParkingSpotsResponse = zParkingSpot;

export const zGetApiParkingSpotsStatusesHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiParkingSpotsStatusesQuery = z.object({
    limit: z.int().optional(),
    page: z.int().optional()
});

/**
 * OK
 */
export const zGetApiParkingSpotsStatusesResponse = zPaginatedResponseModelsParkingSpotStatus;

export const zGetApiParkingSpotsTypesHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiParkingSpotsTypesQuery = z.object({
    limit: z.int().optional(),
    page: z.int().optional()
});

/**
 * OK
 */
export const zGetApiParkingSpotsTypesResponse = zPaginatedResponseModelsParkingSpotType;

export const zDeleteApiParkingSpotsIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zDeleteApiParkingSpotsIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zDeleteApiParkingSpotsIdResponse = zOkResponse;

export const zGetApiParkingSpotsIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiParkingSpotsIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zGetApiParkingSpotsIdResponse = zParkingSpot;

/**
 * Request body for models.ParkingSpot
 */
export const zPutApiParkingSpotsIdBody = zParkingSpot;

export const zPutApiParkingSpotsIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zPutApiParkingSpotsIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zPutApiParkingSpotsIdResponse = zParkingSpot;

export const zGetApiParkingStatsHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zGetApiParkingStatsResponse = zParkingStats;

export const zGetApiParkingTransactionsHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiParkingTransactionsQuery = z.object({
    limit: z.int().optional(),
    page: z.int().optional()
});

/**
 * OK
 */
export const zGetApiParkingTransactionsResponse = zPaginatedResponseModelsParkingTransaction;

/**
 * Request body for models.ParkingTransaction
 */
export const zPostApiParkingTransactionsBody = zParkingTransaction;

export const zPostApiParkingTransactionsHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zPostApiParkingTransactionsResponse = zParkingTransaction;

export const zGetApiParkingTransactionsIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiParkingTransactionsIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zGetApiParkingTransactionsIdResponse = zParkingTransaction;

export const zPostApiParkingTransactionsIdCheckOutHeaders = z.object({
    Accept: z.string().optional()
});

export const zPostApiParkingTransactionsIdCheckOutPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zPostApiParkingTransactionsIdCheckOutResponse = zBool;

export const zGetApiParkingVehiclesHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiParkingVehiclesQuery = z.object({
    limit: z.int().optional(),
    page: z.int().optional()
});

/**
 * OK
 */
export const zGetApiParkingVehiclesResponse = zPaginatedResponseModelsVehicle;

/**
 * Request body for models.Vehicle
 */
export const zPostApiParkingVehiclesBody = zVehicle;

export const zPostApiParkingVehiclesHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zPostApiParkingVehiclesResponse = zVehicle;

export const zDeleteApiParkingVehiclesIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zDeleteApiParkingVehiclesIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zDeleteApiParkingVehiclesIdResponse = zOkResponse;

export const zGetApiParkingVehiclesIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiParkingVehiclesIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zGetApiParkingVehiclesIdResponse = zVehicle;

/**
 * Request body for models.Vehicle
 */
export const zPutApiParkingVehiclesIdBody = zVehicle;

export const zPutApiParkingVehiclesIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zPutApiParkingVehiclesIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zPutApiParkingVehiclesIdResponse = zVehicle;

export const zGetApiPermissionsHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zGetApiPermissionsResponse = zPermissionsResponse;

export const zGetApiPermissionsTemplatesHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiPermissionsTemplatesQuery = z.object({
    limit: z.int().optional(),
    page: z.int().optional()
});

/**
 * OK
 */
export const zGetApiPermissionsTemplatesResponse = zPaginatedResponseModelsPermissionTemplate;

export const zGetApiPermissionsUserUserIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiPermissionsUserUserIdPath = z.object({
    userId: z.string()
});

/**
 * OK
 */
export const zGetApiPermissionsUserUserIdResponse = zUserPermissionsResponse;

export const zPostApiPermissionsUserUserIdTemplateTemplateIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zPostApiPermissionsUserUserIdTemplateTemplateIdPath = z.object({
    userId: z.string(),
    templateId: z.string()
});

/**
 * OK
 */
export const zPostApiPermissionsUserUserIdTemplateTemplateIdResponse = zOkResponse;

export const zDeleteApiPermissionsUserUserIdPermissionIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zDeleteApiPermissionsUserUserIdPermissionIdPath = z.object({
    userId: z.string(),
    permissionId: z.string()
});

/**
 * OK
 */
export const zDeleteApiPermissionsUserUserIdPermissionIdResponse = zOkResponse;

export const zPostApiPermissionsUserUserIdPermissionIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zPostApiPermissionsUserUserIdPermissionIdPath = z.object({
    userId: z.string(),
    permissionId: z.string()
});

/**
 * OK
 */
export const zPostApiPermissionsUserUserIdPermissionIdResponse = zOkResponse;

export const zGetApiReadyzHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zGetApiReadyzResponse = zString;

export const zGetApiReservationHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiReservationQuery = z.object({
    limit: z.int().optional(),
    page: z.int().optional()
});

/**
 * OK
 */
export const zGetApiReservationResponse = zPaginatedResponseModelsReservation;

/**
 * Request body for models.Reservation
 */
export const zPostApiReservationBody = zReservation;

export const zPostApiReservationHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zPostApiReservationResponse = zReservation;

export const zGetApiReservationIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiReservationIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zGetApiReservationIdResponse = zReservation;

/**
 * Request body for models.Reservation
 */
export const zPutApiReservationIdBody = zReservation;

export const zPutApiReservationIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zPutApiReservationIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zPutApiReservationIdResponse = zReservation;

export const zPostApiReservationIdCheckInHeaders = z.object({
    Accept: z.string().optional()
});

export const zPostApiReservationIdCheckInPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zPostApiReservationIdCheckInResponse = zOkResponse;

export const zPostApiReservationIdCheckOutHeaders = z.object({
    Accept: z.string().optional()
});

export const zPostApiReservationIdCheckOutPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zPostApiReservationIdCheckOutResponse = zOkResponse;

export const zGetApiRestaurantBillsHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiRestaurantBillsQuery = z.object({
    limit: z.int().optional(),
    page: z.int().optional()
});

/**
 * OK
 */
export const zGetApiRestaurantBillsResponse = zPaginatedResponseModelsRestaurantBill;

/**
 * Request body for models.RestaurantBill
 */
export const zPostApiRestaurantBillsBody = zRestaurantBill;

export const zPostApiRestaurantBillsHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zPostApiRestaurantBillsResponse = zRestaurantBill;

export const zDeleteApiRestaurantBillsIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zDeleteApiRestaurantBillsIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zDeleteApiRestaurantBillsIdResponse = zOkResponse;

export const zGetApiRestaurantBillsIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiRestaurantBillsIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zGetApiRestaurantBillsIdResponse = zRestaurantBill;

/**
 * Request body for models.RestaurantBill
 */
export const zPutApiRestaurantBillsIdBody = zRestaurantBill;

export const zPutApiRestaurantBillsIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zPutApiRestaurantBillsIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zPutApiRestaurantBillsIdResponse = zRestaurantBill;

export const zPostApiRestaurantBillsIdSettleHeaders = z.object({
    Accept: z.string().optional()
});

export const zPostApiRestaurantBillsIdSettlePath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zPostApiRestaurantBillsIdSettleResponse = zBool;

export const zGetApiRestaurantInventoryHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiRestaurantInventoryQuery = z.object({
    limit: z.int().optional(),
    page: z.int().optional()
});

/**
 * OK
 */
export const zGetApiRestaurantInventoryResponse = zPaginatedResponseModelsInventoryItem;

/**
 * Request body for models.InventoryItem
 */
export const zPostApiRestaurantInventoryBody = zInventoryItem;

export const zPostApiRestaurantInventoryHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zPostApiRestaurantInventoryResponse = zInventoryItem;

export const zDeleteApiRestaurantInventoryIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zDeleteApiRestaurantInventoryIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zDeleteApiRestaurantInventoryIdResponse = zOkResponse;

export const zGetApiRestaurantInventoryIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiRestaurantInventoryIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zGetApiRestaurantInventoryIdResponse = zInventoryItem;

/**
 * Request body for models.InventoryItem
 */
export const zPutApiRestaurantInventoryIdBody = zInventoryItem;

export const zPutApiRestaurantInventoryIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zPutApiRestaurantInventoryIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zPutApiRestaurantInventoryIdResponse = zInventoryItem;

export const zGetApiRestaurantStatsHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zGetApiRestaurantStatsResponse = zRestaurantStats;

export const zGetApiRestaurantTransactionsHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiRestaurantTransactionsQuery = z.object({
    limit: z.int().optional(),
    page: z.int().optional()
});

/**
 * OK
 */
export const zGetApiRestaurantTransactionsResponse = zPaginatedResponseModelsMealTransaction;

/**
 * Request body for models.MealTransaction
 */
export const zPostApiRestaurantTransactionsBody = zMealTransaction;

export const zPostApiRestaurantTransactionsHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zPostApiRestaurantTransactionsResponse = zMealTransaction;

export const zDeleteApiRestaurantTransactionsIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zDeleteApiRestaurantTransactionsIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zDeleteApiRestaurantTransactionsIdResponse = zOkResponse;

export const zGetApiRestaurantTransactionsIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiRestaurantTransactionsIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zGetApiRestaurantTransactionsIdResponse = zMealTransaction;

/**
 * Request body for models.MealTransaction
 */
export const zPutApiRestaurantTransactionsIdBody = zMealTransaction;

export const zPutApiRestaurantTransactionsIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zPutApiRestaurantTransactionsIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zPutApiRestaurantTransactionsIdResponse = zMealTransaction;

export const zGetApiRoomsHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiRoomsQuery = z.object({
    limit: z.int().optional(),
    page: z.int().optional()
});

/**
 * OK
 */
export const zGetApiRoomsResponse = zPaginatedResponseModelsRoom;

/**
 * Request body for models.Room
 */
export const zPostApiRoomsBody = zRoom;

export const zPostApiRoomsHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zPostApiRoomsResponse = zRoom;

export const zGetApiRoomsAmenitiesHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiRoomsAmenitiesQuery = z.object({
    limit: z.int().optional(),
    page: z.int().optional()
});

/**
 * OK
 */
export const zGetApiRoomsAmenitiesResponse = zPaginatedResponseModelsAmenity;

export const zGetApiRoomsStatusesHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiRoomsStatusesQuery = z.object({
    limit: z.int().optional(),
    page: z.int().optional()
});

/**
 * OK
 */
export const zGetApiRoomsStatusesResponse = zPaginatedResponseModelsRoomStatus;

export const zGetApiRoomsTypesHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiRoomsTypesQuery = z.object({
    limit: z.int().optional(),
    page: z.int().optional()
});

/**
 * OK
 */
export const zGetApiRoomsTypesResponse = zPaginatedResponseModelsRoomType;

export const zDeleteApiRoomsIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zDeleteApiRoomsIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zDeleteApiRoomsIdResponse = zOkResponse;

export const zGetApiRoomsIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiRoomsIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zGetApiRoomsIdResponse = zRoom;

/**
 * Request body for models.Room
 */
export const zPutApiRoomsIdBody = zRoom;

export const zPutApiRoomsIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zPutApiRoomsIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zPutApiRoomsIdResponse = zRoom;

export const zGetApiSanaCountriesHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zGetApiSanaCountriesResponse = z.array(zCountry);

export const zGetApiSanaFamilyRelationshipsHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zGetApiSanaFamilyRelationshipsResponse = z.array(zFamilyRelationship);

export const zGetApiSanaGuestsHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zGetApiSanaGuestsResponse = z.array(zSanaGuestResponse);

export const zPostApiSanaGuestsIdSyncHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zPostApiSanaGuestsIdSyncResponse = zSanaGuestResponse;

export const zGetApiSanaNationalitiesHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zGetApiSanaNationalitiesResponse = z.array(zNationality);

export const zGetApiSanaOccupationsHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zGetApiSanaOccupationsResponse = z.array(zOccupation);

export const zGetApiSanaRoomsHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zGetApiSanaRoomsResponse = z.array(zSanaRoomResponse);

export const zPostApiSanaRoomsIdSyncHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zPostApiSanaRoomsIdSyncResponse = zSanaRoomResponse;

export const zPostApiSanaSyncAllHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zPostApiSanaSyncAllResponse = zString;

export const zGetApiSanaTravelReasonsHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zGetApiSanaTravelReasonsResponse = z.array(zTravelReason);

export const zGetApiUsersHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zGetApiUsersResponse = zPaginatedResponseModelsSanitizedUser;

/**
 * Request body for users.userCreateDto
 */
export const zPostApiUsersBody = zUserCreateDto;

export const zPostApiUsersHeaders = z.object({
    Accept: z.string().optional()
});

/**
 * OK
 */
export const zPostApiUsersResponse = zUserCreateResponse;

export const zGetApiUsersIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zGetApiUsersIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zGetApiUsersIdResponse = zSanitizedUser;

/**
 * Request body for users.userUpdateDto
 */
export const zPutApiUsersIdBody = zUserUpdateDto;

export const zPutApiUsersIdHeaders = z.object({
    Accept: z.string().optional()
});

export const zPutApiUsersIdPath = z.object({
    id: z.string()
});

/**
 * OK
 */
export const zPutApiUsersIdResponse = zSanitizedUser;
